---
title: "beta diversity analysis"
output: html_notebook
---



```{r}
load("data-raw/beta_diversity_data_combined.rda")



```



```{r}


beta_diversity_data$Visit.x = as.factor(beta_diversity_data$Visit.x)
beta_diversity_data  = transform(beta_diversity_data, Days = factor(Visit.x, labels=c("D0","D14","D28","D56"), ordered =TRUE))


beta_diversity_data$Groupe_dose.x = as.factor(beta_diversity_data$Groupe_dose.x)
beta_diversity_data  = transform(beta_diversity_data, Product_dose.x = factor(Groupe_dose.x, labels=c("FMP.1","FMP.3","CP.1","CP.3"), ordered =TRUE))

beta_diversity_data$Visit.y = as.factor(beta_diversity_data$Visit.y)
beta_diversity_data  = transform(beta_diversity_data, Days.y = factor(Visit.y, labels=c("D0","D14","D28","D56"), ordered =TRUE))




```



```{r}


#############
# version finale 22-07-2019
############

tiff(file="beta_diversity_genus_BC_JSD_final.tiff", w=900, h=700)

beta_diversity_data %>%
filter(Days == "D0",Group_test=="Within Group") %>%
filter(!(Days.y == "D0" & Subject_test=="Within Subject")) %>%
ggboxplot(y="value",x="Days.y",color="Subject_test",
fill="Subject_test",alpha=0.5,palette=c("#00AFBB", "#E7B800"),
ylab ="Microbiota beta-diversity\ndistance metrics",xlab="Days", ggtheme = theme_pubr()) +
theme(legend.position = 'bottom')+
facet_grid(variable~Product_dose.x, scales = "free_y")+
theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.text.y = element_text(size=13, color="white", face="bold"))+
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
theme(axis.title.x = element_text(color="black", face="bold", size=15),
axis.title.y = element_text(color="black", size=15, face="bold"),
axis.text.y = element_text(color="black", size=10, face="bold"),
axis.text.x = element_text(color="black", size=12, face="bold"),
legend.text = element_text(color="black", size=12, face="bold"),
legend.title = element_text(color="black", size=13, face="bold")) 

dev.off()




```




```{r}

# does between > within per days and per method ?

beta_diversity_data %>%
filter(Days == "D0",Group_test=="Within Group") %>%
filter(!(Days.y == "D0" & Subject_test=="Within Subject")) %>%
filter(Days.y != "D0")  %>%
tidyr::nest(-Days.y,-Groupe_dose.x, -variable) %>%
  mutate(fit = purrr::map(data, ~ wilcox.test(.$value~.$Subject_test)),
         results = map(fit, broom::glance)) %>% 
  tidyr::unnest(results) %>%
  select(-data,-fit,-statistic,-alternative)



```






```{r}

# a difference between days within subject per method and per group ?

  
  
beta_diversity_data %>%
  filter(Days == "D0",Group_test=="Within Group") %>%
  filter(!(Days.y == "D0"),Subject_test=="Within Subject") %>% 
  tidyr::nest(-Groupe_dose.x, -variable) %>%
  mutate(fit = purrr::map(data, ~ kruskal.test(.$value~.$Days.y)),
         results = map(fit, broom::glance)) %>% 
  tidyr::unnest(results) %>%
  select(-data,-fit,-statistic,-parameter) 
  


```



