---
title: "Compute beta diversity"
output: html_notebook
---



```{r}

devtools::load_all(reset=FALSE)

library(dplyr)



```


```{r}

load("genus.rda")

load("otu.rda")

```


## compute JSD distance

- at genus level

```{r}

tolerance_genus_JSD = 
  genus %>% 
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::dist.JSD()

save(tolerance_genus_JSD, file="tolerance_genus_JSD.rda")

```



- at OTU level

```{r}


tolerance_otu_JSD = 
  otu %>% 
  as.data.frame() %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  #tibble::column_to_rownames("otu") %>%
  BiotypeR::dist.JSD()

save(tolerance_otu_JSD, file="tolerance_otu_JSD.rda")



```





## compute Bray-Curtis dissimilarity

- at genus level


```{r}

tolerance_genus_BC = 
  genus %>% 
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  t %>%
  vegan::vegdist(method="bray")

save(tolerance_genus_BC, file="tolerance_genus_BC.rda")

```


- at otu level



```{r}

tolerance_genus_BC = 
  otu %>% 
  as.data.frame %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  #tibble::column_to_rownames("otu") %>%
  t %>%
  vegan::vegdist(method="bray")

save(tolerance_genus_BC, file="tolerance_otu_BC.rda")

```





import unweigthed and weigthed UNIFRAC from qiime

```{r}

readr::read_tsv(system.file("distance/weighted_unifrac_dm.txt", package="Tolerance")) %>%
  tibble::column_to_rownames("X1") %>%
  as.dist() -> tolerance_unifrac


save(tolerance_unifrac, file="tolerance_unifrac.rda")

```



```{r}

readr::read_tsv(system.file("distance/unweighted_unifrac_dm.txt", package="Tolerance")) %>%
  tibble::column_to_rownames("X1") %>%
  as.dist() -> tolerance_unifrac_UW


save(tolerance_unifrac, file="tolerance_unifrac_UW.rda")


```







