---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}

```


## global time effect
```{r}

Tolerance::sample_metadata_metaG_v2v4_allvisit %>% head

sample_metadata_metaG_v2v4_allvisit$Groupe_dose = as.factor(sample_metadata_metaG_v2v4_allvisit$Groupe_dose)
sample_metadata_metaG_v2v4_allvisit$Groupe_dose = relevel(sample_metadata_metaG_v2v4_allvisit$Groupe_dose, ref = "CP.3")

sample_metadata_metaG_v2v4_allvisit$samplenr = as.character(sample_metadata_metaG_v2v4_allvisit$samplenr)
sample_metadata_metaG_v2v4_allvisit$Subject = as.factor(sample_metadata_metaG_v2v4_allvisit$Subject) # je mets subject en factor sinon il me met un warning avec la fonction DESeqDataSetFromMatrix
sample_metadata_metaG_v2v4_allvisit$Sample = as.character(sample_metadata_metaG_v2v4_allvisit$Sample)

devtools::use_data(sample_metadata_metaG_v2v4_allvisit, overwrite = TRUE)


data(MSP_abundance_matrix_rounded_5p)
#527 MSP

MSP_abundance_matrix_rounded_5p_v2v4_allvisit = MSP_abundance_matrix_rounded_5p[match(sample_metadata_metaG_v2v4_allvisit$samplenr, colnames(MSP_abundance_matrix_rounded_5p))]

MSP_abundance_matrix_rounded_5p_v2v4_allvisit$msp = rownames(MSP_abundance_matrix_rounded_5p_v2v4_allvisit)
MSP_abundance_matrix_rounded_5p_v2v4_allvisit %>% head

MSP_abundance_matrix_rounded_5p_v2v4_allvisit %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("msp") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> MSP_select

MSP_abundance_matrix_rounded_5p_v2v4_allvisit = MSP_abundance_matrix_rounded_5p_v2v4_allvisit[MSP_select,]
MSP_abundance_matrix_rounded_5p_v2v4_allvisit = MSP_abundance_matrix_rounded_5p_v2v4_allvisit[, -81]
#469 MSP

t(MSP_abundance_matrix_rounded_5p_v2v4_allvisit) -> MSP_abundance_matrix_rounded_5p_v2v4_allvisit
MSP_abundance_matrix_rounded_5p_v2v4_allvisit = as.data.frame (MSP_abundance_matrix_rounded_5p_v2v4_allvisit)


sample_metadata_metaG_v2v4_allvisit = as.data.frame(sample_metadata_metaG_v2v4_allvisit)
sample_metadata_metaG_v2v4_allvisit$Groupe_dose = as.factor(sample_metadata_metaG_v2v4_allvisit$Groupe_dose)
sample_metadata_metaG_v2v4_allvisit$Groupe_dose = relevel(sample_metadata_metaG_v2v4_allvisit$Groupe_dose, ref = "CP.3")

Tolerance::sample_metadata_metaG_v2v4_allvisit %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head




dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_5p_v2v4_allvisit[Tolerance::sample_metadata_metaG_v2v4_allvisit$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_v2v4_allvisit %>%  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject, fitType='local')


results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)
# 
# msp
# <chr>
# baseMean
# <dbl>
# log2FoldChange
# <dbl>
# lfcSE
# <dbl>
# stat
# <dbl>
# msp_0331	6.015346	-1.526151	0.9927073	62.58175	
# msp_lrhamnosus	3.507857	1.863893	1.3058375	47.31404	

results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(padj)

# msp
# <chr>
# baseMean
# <dbl>
# log2FoldChange
# <dbl>
# lfcSE
# <dbl>
# stat
# <dbl>
# msp_0331	6.015346	-1.5261513	0.9927073	62.58175	
# msp_lrhamnosus	3.507857	1.8638934	1.3058375	47.31404	
# msp_1025	2.660730	0.9980511	1.2250908	22.77616	-> L casei

```

## effect product visit

```{r}
# sans appariement ----------

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_5p_v2v4_allvisit[Tolerance::sample_metadata_metaG_v2v4_allvisit$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_v2v4_allvisit %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Groupe + Visit:Groupe)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Visit+Groupe, fitType='local')

results(dds_res1) %>% as.data.frame() %>%
      tibble::rownames_to_column("msp") %>% filter(padj < 0.05)
# msp_0039	48.739923	-5.218771	1.2239489	16.41453	
# msp_0052	6.607301	-3.699086	1.0254072	12.60940	
# msp_0242	3.872368	3.249096	0.8999013	12.95701	
# msp_lrhamnosus	3.507857	-2.221641	0.6475787	11.72361	
# msp_0202


results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(padj)
# msp_0039	48.739923	-5.218771	1.2239489	16.41453	5.089374e-05	
# msp_0202	3.265949	-3.467399	0.8481196	16.74849	4.267617e-05	
# msp_0052	6.607301	-3.699086	1.0254072	12.60940	3.838118e-04	
# msp_0242


# en gardant appariement ------


dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_5p_v2v4_allvisit[Tolerance::sample_metadata_metaG_v2v4_allvisit$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_v2v4_allvisit %>%  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject, fitType='local')



temp <- Tolerance::sample_metadata_metaG_v2v4_allvisit #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.3") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod, fitType='local')

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]
# 

dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)


results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(pvalue)
# 0 MSP !!!

results(dds2_res1) %>% as.data.frame() %>%
      tibble::rownames_to_column("msp") %>% filter(padj < 0.05)
# 0 MSP !!!



dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)


DESeq2::resultsNames(dds2_res2)


res_ATN3_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05.rda")
# 0 MSP !!!



```
