---
title: "Differential analysis with MSP"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```



```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}

```



```{r}

data(MSP_abundance_matrix_rounded)

MSP_abundance_matrix_rounded$msp = rownames(MSP_abundance_matrix_rounded)
MSP_abundance_matrix_rounded %>% head


Tolerance::sample_metadata_metaG %>% head
str(sample_metadata_metaG$samplenr)
sample_metadata_metaG$samplenr = as.character(sample_metadata_metaG$samplenr)
str(sample_metadata_metaG$Subject)
sample_metadata_metaG$Subject = as.factor(sample_metadata_metaG$Subject) # je mets subject en factor sinon il me met un warning avec la fonction DESeqDataSetFromMatrix
str(sample_metadata_metaG$Sample)
sample_metadata_metaG$Sample = as.character(sample_metadata_metaG$Sample)

sample_metadata_metaG$Groupe_dose = as.factor(sample_metadata_metaG$Groupe_dose)
sample_metadata_metaG$Groupe_dose = relevel(sample_metadata_metaG$Groupe_dose, ref = "CP.3") 
devtools::use_data(sample_metadata_metaG, overwrite = TRUE)

```


## Filter abundant MSP
```{r}

MSP_abundance_matrix_rounded %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("msp") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> MSP_select
#745 MSP

# MSP_abundance_matrix_rounded %>%
#   mutate_if(is.numeric,function(x)(x/sum(x))) %>%
#   tibble::column_to_rownames("msp") %>%
#   BiotypeR::noise.removal(percent=0.2) %>% rownames() -> MSP_select
# #587
# 
# MSP_abundance_matrix_rounded %>%
#   mutate_if(is.numeric,function(x)(x/sum(x))) %>%
#   tibble::column_to_rownames("msp") %>%
#   BiotypeR::noise.removal(percent=0.5) %>% rownames() -> MSP_select
# #412

# MSP_abundance_matrix %>%
#   filter(MSP_abundance_matrix %in% MSP_select) %>%
#   tibble::column_to_rownames("msp") %>%
#   t %>% as.data.frame -> MSP_abundance_matrix_count

MSP_abundance_matrix_rounded = MSP_abundance_matrix_rounded[MSP_select,]
MSP_abundance_matrix_rounded = MSP_abundance_matrix_rounded[, -108]

t(MSP_abundance_matrix_rounded) -> MSP_abundance_matrix_rounded
MSP_abundance_matrix_rounded = as.data.frame (MSP_abundance_matrix_rounded)


Tolerance::sample_metadata_metaG %>%
  tibble::column_to_rownames("samplenr") %>% head


```


## global time effect
```{r}

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded[Tolerance::sample_metadata_metaG$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)
# estimating size factors
# estimating dispersions
# gene-wise dispersion estimates
# mean-dispersion relationship
# -- note: fitType='parametric', but the dispersion trend was not well captured by the
#    function: y = a/x + b, and a local regression fit was automatically substituted.
#    specify fitType='local' or 'mean' to avoid this message next time.
# final dispersion estimates
# fitting model and testing

save(dds_res1, file="deseq2_dds_res1_analysis_MSP.rda")


dds_res1_fittypelocal <- DESeq(dds, test="LRT",  reduced= ~Subject, fitType='local')


results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# signicant : L rhamnosus (+), Clostridium leptum (-)

results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.5) %>%
  arrange(padj)

# signicant : L rhamnosus (+), L casei paracasei (+), Clostridium leptum (-)


dds_res1_fittypelocal <- DESeq(dds, test="LRT",  reduced= ~Subject, fitType='local')
save(dds_res1_fittypelocal, file="deseq2_dds_res1_analysis_MSP_fittypelocal.rda")

results(dds_res1_fittypelocal, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)
# signicant : L rhamnosus (+), Clostridium leptum (-)

results(dds_res1_fittypelocal, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(padj)
# signicant : L rhamnosus (+), L casei paracasei (+), Clostridium leptum (-)

```


## Specific group effect and visit

```{r}

temp <- Tolerance::sample_metadata_metaG #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.3") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod,fitType='local')

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)
# using supplied model matrix
# 1 rows did not converge in beta, labelled in mcols(object)$fullBetaConv. Use larger maxit argument with nbinomLRT
save(dds2_res1, file="deseq2_dds2_res1_analysis_MSP_fittypelocal.rda")

results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# pas de Lactobacillus rhmano ou casei qui ressort

dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)
# using supplied model matrix
# 1 rows did not converge in beta, labelled in mcols(object)$betaConv. Use larger maxit argument with nbinomWaldTest

DESeq2::resultsNames(dds2_res2)
# [1] "Intercept"                     "Groupe_doseATN.3"             
#  [3] "Groupe_doseCP.3.subject.nS10"  "Groupe_doseATN.3.subject.nS10"
#  [5] "Groupe_doseCP.3.subject.nS11"  "Groupe_doseATN.3.subject.nS11"
#  [7] "Groupe_doseCP.3.subject.nS12"  "Groupe_doseATN.3.subject.nS12"
#  [9] "Groupe_doseCP.3.subject.nS13"  "Groupe_doseATN.3.subject.nS13"
# [11] "Groupe_doseCP.3.subject.nS14"  "Groupe_doseATN.3.subject.nS14"
# [13] "Groupe_doseCP.3.subject.nS15"  "Groupe_doseATN.3.subject.nS15"
# [15] "Groupe_doseCP.3.subject.nS16"  "Groupe_doseATN.3.subject.nS16"
# [17] "Groupe_doseCP.3.subject.nS17"  "Groupe_doseATN.3.subject.nS17"
# [19] "Groupe_doseCP.3.subject.nS18"  "Groupe_doseATN.3.subject.nS18"
# [21] "Groupe_doseCP.3.subject.nS19"  "Groupe_doseATN.3.subject.nS19"
# [23] "Groupe_doseCP.3.subject.nS2"   "Groupe_doseATN.3.subject.nS2" 
# [25] "Groupe_doseCP.3.subject.nS20"  "Groupe_doseATN.3.subject.nS20"
# [27] "Groupe_doseCP.3.subject.nS21"  "Groupe_doseATN.3.subject.nS21"
# [29] "Groupe_doseCP.3.subject.nS22"  "Groupe_doseATN.3.subject.nS22"
# [31] "Groupe_doseCP.3.subject.nS23"  "Groupe_doseATN.3.subject.nS23"
# [33] "Groupe_doseCP.3.subject.nS24"  "Groupe_doseCP.3.subject.nS3"  
# [35] "Groupe_doseATN.3.subject.nS3"  "Groupe_doseCP.3.subject.nS4"  
# [37] "Groupe_doseATN.3.subject.nS4"  "Groupe_doseCP.3.subject.nS5"  
# [39] "Groupe_doseATN.3.subject.nS5"  "Groupe_doseCP.3.subject.nS6"  
# [41] "Groupe_doseATN.3.subject.nS6"  "Groupe_doseCP.3.subject.nS7"  
# [43] "Groupe_doseATN.3.subject.nS7"  "Groupe_doseCP.3.subject.nS8"  
# [45] "Groupe_doseATN.3.subject.nS8"  "Groupe_doseCP.3.subject.nS9"  
# [47] "Groupe_doseATN.3.subject.nS9"  "Groupe_doseCP.3.VisitV4"      
# [49] "Groupe_doseATN.3.VisitV4"      "Groupe_doseATN.3.VisitV5" 

save(dds2_res2, file="deseq2_dds2_res2_analysis_MSP.rda" )


res_ATN3_CP3_v2v4_MSP=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("msp")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05.rda")

results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"),alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(padj)

# significant : msp_0127 (Ruminococcus)
```


## supprime les v5 dans le sample_metadata_metaG file


```{r}

Tolerance::sample_metadata_metaG %>% head

sample_metadata_metaG_v2v4 = sample_metadata_metaG[sample_metadata_metaG$Visit=="V2" | sample_metadata_metaG$Visit=="V4",]
sample_metadata_metaG_v2v4 %>% head
sample_metadata_metaG_v2v4$Groupe_dose = as.factor(sample_metadata_metaG_v2v4$Groupe_dose)
sample_metadata_metaG_v2v4$Groupe_dose = relevel(sample_metadata_metaG_v2v4$Groupe_dose, ref = "CP.3") 
devtools::use_data(sample_metadata_metaG_v2v4, overwrite = TRUE)


data(MSP_abundance_matrix_rounded)

MSP_abundance_matrix_rounded_v2v4 = MSP_abundance_matrix_rounded[match(sample_metadata_metaG_v2v4$samplenr, colnames(MSP_abundance_matrix_rounded))]

MSP_abundance_matrix_rounded_v2v4$msp = rownames(MSP_abundance_matrix_rounded_v2v4)
MSP_abundance_matrix_rounded_v2v4 %>% head


MSP_abundance_matrix_rounded_v2v4 %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("msp") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> MSP_select

MSP_abundance_matrix_rounded_v2v4 = MSP_abundance_matrix_rounded_v2v4[MSP_select,]
MSP_abundance_matrix_rounded_v2v4 = MSP_abundance_matrix_rounded_v2v4[, -86]

t(MSP_abundance_matrix_rounded_v2v4) -> MSP_abundance_matrix_rounded_v2v4
MSP_abundance_matrix_rounded_v2v4 = as.data.frame (MSP_abundance_matrix_rounded_v2v4)

#sample_metadata_metaG_v2v4 = as.data.frame(sample_metadata_metaG_v2v4)

Tolerance::sample_metadata_metaG_v2v4 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
# Error: `df` must be a data frame without row names in `column_to_rownames()`.
# Call `rlang::last_error()` to see a backtrace


dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_v2v4[Tolerance::sample_metadata_metaG_v2v4$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_v2v4 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Groupe + Visit:Groupe)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Visit+Groupe)

results(dds_res1) %>% as.data.frame() %>%
      tibble::rownames_to_column("msp") %>% filter(padj < 0.05)

```



