---
title: |-
  Differential analysis
  work on Lactobacillus (ATN.3 & CP.3 - V2 & V4)
output:
  html_document:
    df_print: paged
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}



```



```{r}

load("data/genus.rda")
load("data/sample_metadata.rda")

sample_metadata$Groupe = as.factor(sample_metadata$Groupe)
str(sample_metadata$Groupe)
sample_metadata$Groupe = relevel(sample_metadata$Groupe, ref = "CP") 
# > str(sample_metadata$Groupe)
#  Factor w/ 2 levels "CP","ATN": 1 2 2 1 2 2 2 1 2 1 ...
sample_metadata$Groupe_dose = as.factor(sample_metadata$Groupe_dose)
sample_metadata$Groupe_dose = relevel(sample_metadata$Groupe_dose, ref = "CP.1") rownames(sample_metadata)<-sample_metadata$samplenr


# Sujets qui ne sont pas presents a tous les points de temps
table(sample_metadata$Subject)[table(sample_metadata$Subject) != 4]
# 276001004 276001018 276001028 276001054 276001061 276001076 276001077 276001092 276001117
idSub_misPt<-names(table(sample_metadata$Subject)[table(sample_metadata$Subject) != 4]
)

table(sample_metadata$Subject[sample_metadata$Subject %in% idSub_misPt], sample_metadata$Visit[sample_metadata$Subject %in% idSub_misPt])
#           V2 V3 V4 V5
# 276001004  1  1  0  1 *
# 276001018  1  1  0  1 *
# 276001028  1  1  0  0 *
# 276001054  1  0  1  1   CP.3
# 276001061  1  1  1  0   CP.3
# 276001076  1  1  1  0   ATN.1
# 276001077  1  1  0  0 *
# 276001092  0  1  1  1 *
# 276001117  1  1  1  0   ATN.1

# table(sample_metadata$Subject[sample_metadata$Subject %in% idSub_misPt], sample_metadata$Visit[sample_metadata$Subject %in% idSub_misPt], sample_metadata$Groupe_dose[sample_metadata$Subject %in% idSub_misPt])


```


## Filter abundant taxa
```{r}

genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select



genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata %>%
  tibble::column_to_rownames("samplenr") %>% head
  


```


## Specific group effect and visit
```{r}

## Ajout de l'identifiant sujet specifique a DESeq2
temp <- sample_metadata #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.1") 

temp$Groupe = as.factor(temp$Groupe)
temp$Groupe = relevel(temp$Groupe, ref = "CP") 


# DESeq2 object and design matrices
dds3 <- DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[sample_metadata$samplenr,]),
  colData = sample_metadata %>% tibble::column_to_rownames("samplenr"),
  # colData = sample_metadata,
  design = ~ 1)

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]

# Model estimation
dds3 <- estimateSizeFactors(dds3, type="poscounts")
dds3 <- estimateDispersions(dds3, modelMatrix = mod)
# save(dds3, temp, file="./data/export_local.RData")

## Travail sur Lactobacillus pour essayer d'expliquer pourquoi pas significatif à V4 entre ATN3 et CP3 comme attendu par MFH

## LRT
dds3_resLRT <- nbinomLRT(dds3, full = mod, reduced = mod2)
save(dds3_resLRT, file="dds3_resLRT.rda")

## Wald
# Group comparisons at each time point
dds3_resWald = nbinomWaldTest(dds3, modelMatrix = mod, betaPrior = FALSE)
save(dds3_resWald, file="dds3_resWald.rda" )
#using supplied model matrix
#67 rows did not converge in beta, labelled in mcols(object)$betaConv. Use larger maxit argument with nbinomWaldTest


# id LactoB
idx_lactob<-grep("Lactobacillus", rownames(results(dds3_resLRT)))

## Verifie la convergence de LactoB
mcols(dds3_resLRT)[idx_lactob, "fullBetaConv"]
# TRUE

results(dds3_resLRT, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)



```

## Analyse du comportement de Lactobacillus a V2 et V4 pour ATN3 et CP3
```{r}
## Donnees normalisees par DESeq2
normCounts<-counts(dds3, normalized=TRUE)

# Index de LactoB
idx_lactobNorm<-grep("Lactobacillus", rownames(normCounts))


# Extraction des id d'interet - ATN3 et CP3 a V2 et V4
idx_set1<-sample_metadata %>% filter(Visit %in% c("V2", "V4")) %>% filter(Groupe_dose %in% c("ATN.3", "CP.3")) %>% dplyr::select(samplenr) %>% c()

# Extraction des donnees d'interet
lactoB_set1<-data.frame(Lactobacillus=normCounts[idx_lactobNorm, idx_set1[[1]]])
lactoB_set1$samplenr<-rownames(lactoB_set1)
lactoB_set1<-merge(lactoB_set1, sample_metadata, by="samplenr")

## Boxplot V2 V4
gp_set1<-ggplot(lactoB_set1, aes(x=Visit, y=Lactobacillus, fill=Groupe_dose))+geom_boxplot()
gp_set1<-gp_set1+ggtitle("Lactobacillus (DESeq2 normalized counts)")
print(gp_set1)
## Echelle log10
gp_set1<-gp_set1+scale_y_log10()
gp_set1<-gp_set1+ggtitle("Lactobacillus (DESeq2 normalized counts)\n(log10-scaled)")
print(gp_set1)
# => les medianes sont visuellement bien distinctes mais les intervalles interquartiles (verifier que c'est bien ce que la fonction affiche !) se chevauchent
# => non significativite liee a la variabilite ?
# => un point de CP3 a V2 a une valeur tres elevee


## Calcul du log-ratio V4/V2
lactoB_set1_V4sV2<-merge(lactoB_set1[lactoB_set1$Visit == "V4", ], lactoB_set1[lactoB_set1$Visit == "V2", c(2, 4)], by="Subject", suffixes=c("_V4", "_V2"))

lactoB_set1_V4sV2$ratio<-lactoB_set1_V4sV2$Lactobacillus_V4/lactoB_set1_V4sV2$Lactobacillus_V2
lactoB_set1_V4sV2$logratio<-log(lactoB_set1_V4sV2$Lactobacillus_V4/lactoB_set1_V4sV2$Lactobacillus_V2)
lactoB_set1_V4sV2$change_sub<-lactoB_set1_V4sV2$Lactobacillus_V4-lactoB_set1_V4sV2$Lactobacillus_V2

gp_set1_lgr<-ggplot(lactoB_set1_V4sV2, aes(x=Groupe_dose, y=logratio, fill=Groupe_dose, shape=Groupe_dose))+geom_boxplot()+geom_jitter()
gp_set1_lgr<-gp_set1_lgr+ggtitle("log ratio V4/V2 - Lactobacillus (DESeq2 normalized counts)")
print(gp_set1_lgr)
# => idem, medianes visuallement differentes mais chevauvement des interquartiles


## Correlation entre comptages brutes et comptages normalises
idx_lactobRaw<-grep("Lactobacillus", genus$genus)

lactoB_set1_raw<-as(genus[idx_lactobRaw, idx_set1[[1]]], "numeric")
names(lactoB_set1_raw)<-idx_set1[[1]]
lactoB_set1_norm<-normCounts[idx_lactobNorm, idx_set1[[1]]]
# Verification des ordres
all(names(lactoB_set1_raw) == names(lactoB_set1_norm)) # => OK, meme ordre

plot(lactoB_set1_norm, lactoB_set1_raw)
# On remarque qu'un point semble diminuer la linearite de la relation
which(lactoB_set1_raw > 5000)
# 152581 
#   84
sample_metadata %>% filter(samplenr == "152581")
# samplenr  Visit Subject   Groupe Doses Groupe_dose SCP_Date
#  152581   V2    276001054 CP         3 CP.3        14.04.2010


cor.test(lactoB_set1_norm, lactoB_set1_raw, method="pearson")
# t = 21.461, df = 87, p-value < 2.2e-16
# cor = 0.9171271
# 0.9171271² = 0.8411221
# => bien mais pas top...

## Sans le 152581
cor.test(lactoB_set1_norm[names(lactoB_set1_norm) != "152581"], lactoB_set1_raw[names(lactoB_set1_raw) != "152581"], method="pearson")
# t = 30.635, df = 86, p-value < 2.2e-16
# cor = 0.9571089
# 0.9571089² = 0.9160574
# => deja mieux !


## Est-ce que ce sujet a egalement une valeur elevee a V4 ?
# En plus c'est un sujet a qui il manque un point de temps...
idSub_pbl<-sample_metadata %>% filter(samplenr == "152581") %>% dplyr::select(Subject)
# 276001054

table(sample_metadata[sample_metadata$Subject == "276001054", "Visit"])
# V2 V4 V5 
#  1  1  1

# idSampl_pbl<-sample_metadata %>% filter(Subject == idSub_pbl[[1]], Visit %in% c("V2", "V4")) %>% dplyr::select(samplenr)
idSampl_pbl<-sample_metadata %>% filter(Subject == idSub_pbl[[1]]) %>% dplyr::select(samplenr)


normCounts[idx_lactobNorm, idSampl_pbl[[1]]]
#   152275     152352     152581 
# 79.33796 1154.26794 2317.59254
#   V4        V3          V4
# => V4 dans la moyenne haute mais pas aberrant
# => le V3 semble haut mais a verifier



## Graphe change from baseline
lactoB_set1_baseline_change<-rbind(lactoB_set1_V4sV2[, c(colnames(lactoB_set1)[-2], "change_sub")],
                                   cbind(lactoB_set1[lactoB_set1$Visit == "V2", -2], data.frame(change_sub = 0)))
lactoB_set1_baseline_change$Visit_num<-2
lactoB_set1_baseline_change$Visit_num[lactoB_set1_baseline_change$Visit == "V4"]<-4

gp_change<-ggplot(lactoB_set1_baseline_change, aes(x=Visit_num, y=change_sub, group=Subject, color=Groupe_dose))+geom_point()+geom_line()
gp_change<-gp_change+scale_x_continuous(name="Visit", breaks=c(2, 4), labels=c("V2", "V4"))
print(gp_change)


# Sans le point 152581 (sujet associe)
gp_change_2<-ggplot(lactoB_set1_baseline_change %>% filter(Subject != idSub_pbl[[1]]), aes(x=Visit_num, y=change_sub, group=Subject, color=Groupe_dose))+geom_point()+geom_line()
gp_change_2<-gp_change_2+scale_x_continuous(name="Visit", breaks=c(2, 4), labels=c("V2", "V4"))
print(gp_change_2)


```


```{r}

# ATN3 vs CP3 by Visit

res_ATN3_CP3_v2=
results(dds2_res2, contrast = list("Groupe_doseATN.3","Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") #  %>% filter(padj<0.05)
# save(res_ATN3_CP3_v2, file="res_ATN3_CP3_v2_p0.05.rda")

res_ATN3_CP3_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") #  %>% filter(padj<0.05)
# save(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05.rda")

res_ATN3_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") #  %>% filter(padj<0.05)
# save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05.rda")

res_ATN3_CP3_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") #  %>% filter(padj<0.05)
# save(res_ATN3_CP3_v2v5, file="res_ATN3_CP3_v2v5_p0.05.rda")


res_ATN3_CP3_v2[idx_lactobNorm, ]
# baseMean log2FoldChange    lfcSE      stat      pvalue       padj
# 229.6484      -4.894104 1.689695 -2.896442 0.003774208 0.02974964
res_ATN3_CP3_v2v3[idx_lactobNorm, ]
#  baseMean log2FoldChange    lfcSE     stat    pvalue      padj
# 229.6484       1.153944 0.872936 1.321911 0.1861976 0.5874257
res_ATN3_CP3_v2v4[idx_lactobNorm, ]
# baseMean log2FoldChange     lfcSE     stat    pvalue      padj
# 229.6484       1.060401 0.8927755 1.187758 0.2349289 0.5370975
res_ATN3_CP3_v2v5[idx_lactobNorm, ]
# baseMean log2FoldChange     lfcSE      stat    pvalue      padj
# 229.6484      0.1759995 0.8908144 0.1975715 0.8433803 0.9417747
```


```{r}

## Essai de retirer le sujet 276001054 car il a ete identifie comme ayant une forte valeur de LactoB a baseline (et c'est un Control - CP3) donc cela peut biaiser la normalisation


# sample ID associes au sujet 276001054
id_276001054<-sample_metadata$samplenr[sample_metadata$Subject == "276001054"]

# Nettoyage de la table des comptages
genus_count_2<-genus_count[!rownames(genus_count) %in% id_276001054, ]

# Nettoyade des metadonnes
temp_2<-sample_metadata[!sample_metadata$samplenr %in% id_276001054, ]

temp_2 <- temp_2 #%>% tibble::column_to_rownames("samplenr")
temp_2 <- temp_2[with(temp_2, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp_2), 
                                temp_2$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp_2 = full_join(temp_2, 
                  new_sub, 
                  by = "Subject")
rownames(temp_2) <- temp_2$samplenr

temp_2 # need here to force level factor

temp_2$Groupe_dose = as.factor(temp_2$Groupe_dose)
temp_2$Groupe_dose = relevel(temp_2$Groupe_dose, ref = "CP.1") 

temp_2$Groupe = as.factor(temp_2$Groupe)
temp_2$Groupe = relevel(temp_2$Groupe, ref = "CP") 

# Mise en ordre des 2 tables
rownames(temp_2)<-temp_2$samplenr
temp_2<-data.frame(temp_2)
temp_2<-temp_2[rownames(genus_count_2), ]



dds_test1 = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count_2[temp_2$samplenr,]), 
  colData = temp_2, 
  # design = ~ Visit + Subject)
  design = ~ 1)

# Full design matrix
mod_test1 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp_2)
mod_test1 <- mod_test1[,colSums(mod_test1)>0]

# Reduced design matrix
mod2_test1 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp_2)
mod2_test1 = mod2_test1[, colSums(mod2_test1)>0]


# Model
dds_test1 <- estimateSizeFactors(dds_test1, type="poscounts")
dds_test1 <- estimateDispersions(dds_test1, modelMatrix = mod_test1)


## Verification de la normalisation
normCounts_test1<-counts(dds_test1, normalized=T)

## Correlation entre comptages brutes et comptages normalises
idx_lactobNorm_test1<-grep("Lactobacillus", rownames(normCounts_test1))
# set1 - ATN3 et CP3 a V2 et V4
idx_test1<-temp_2 %>% filter(Visit %in% c("V2", "V4")) %>% filter(Groupe_dose %in% c("ATN.3", "CP.3")) %>% dplyr::select(samplenr) %>% c()

idx_lactob_test1Raw<-grep("Lactobacillus", genus$genus)
lactob_test1Raw<-as(genus[idx_lactob_test1Raw, idx_test1[[1]]], "numeric")
names(lactob_test1Raw)<-idx_test1[[1]]
lactoB_test1Norm<-normCounts_test1[idx_lactobNorm_test1, idx_test1[[1]]]
all(names(lactob_test1Raw) == names(lactoB_test1Norm)) # => OK, meme ordre

plot(lactoB_test1Norm, lactob_test1Raw)
# => par rapport aux donnes avec le sujet 276001054, il y a du mieux car plus de point extreme


# Extraction des donnees d'interet
lactoB_test1<-data.frame(Lactobacillus=normCounts_test1[idx_lactobNorm_test1, idx_test1[[1]]])
lactoB_test1$samplenr<-rownames(lactoB_test1)
lactoB_test1<-merge(lactoB_test1, sample_metadata, by="samplenr")

## Boxplot V2 V4
gp_test1<-ggplot(lactoB_test1, aes(x=Visit, y=Lactobacillus, fill=Groupe_dose))+geom_boxplot()
gp_test1<-gp_test1+ggtitle("Lactobacillus (DESeq2 normalized counts)")
print(gp_test1)
## Echelle log10
gp_test1<-gp_test1+scale_y_log10()
gp_test1<-gp_test1+ggtitle("Lactobacillus (DESeq2 normalized counts)\n(log10-scaled)")
print(gp_test1)

```


```{r}

## Tests LRT + Wald
dds_test1_resLRT <- nbinomLRT(dds_test1, full = mod_test1, reduced = mod2_test1)
save(dds_test1_resLRT, file="/data/dds_test1_resLRT.rda")

dds_test1_resWald = nbinomWaldTest(dds_test1, modelMatrix = mod_test1, betaPrior = FALSE)
save(dds_test1_resWald, file="/data/dds_test1_resWald.rda")


# ATN3 vs CP3 by Visit

restest1_ATN3_CP3_v2=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3","Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")

restest1_ATN3_CP3_v2v3=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")

restest1_ATN3_CP3_v2v4=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")

restest1_ATN3_CP3_v2v5=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")

restest1_ATN3_CP3_v2[idx_lactobNorm, ]
# baseMean log2FoldChange    lfcSE    stat    pvalue      padj
# 219.8503       1.796545 1.414836 1.26979 0.2041594 0.3198566
restest1_ATN3_CP3_v2v3[idx_lactobNorm, ]
# baseMean log2FoldChange     lfcSE     stat       pvalue        padj
# 219.8503       3.202131 0.7151175 4.477769 7.542728e-06 0.001010726
restest1_ATN3_CP3_v2v4[idx_lactobNorm, ]
# baseMean log2FoldChange     lfcSE     stat       pvalue        padj
# 219.8503       3.216879 0.7363164 4.368881 1.248846e-05 0.001673454
restest1_ATN3_CP3_v2v5[idx_lactobNorm, ]
# baseMean log2FoldChange    lfcSE       stat    pvalue padj
# 219.8503     -0.5381651 0.734835 -0.7323619 0.4639477    1


```
