---
title: "Differential analysis -16S-samples with v2 and v4 visits"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}

```

# selection of subjects with minimal visits v2 and v4 
```{r}
# variable v2_v4 to select subjects with min v2 and v4

sample_metadata_allv2_v4 = read.csv2("~/tolerance/data/sample_metadata_allv2_v4.csv")
sample_metadata_allv2_v4 = sample_metadata_allv2_v4[sample_metadata_allv2_v4$v2_v4=="1",]
#336 samples (instead of 349)

sample_metadata_allv2_v4$samplenr = as.character(sample_metadata_allv2_v4$samplenr)
sample_metadata_allv2_v4$Subject = as.character(sample_metadata_allv2_v4$Subject)
sample_metadata_allv2_v4$Groupe_dose = as.factor(sample_metadata_allv2_v4$Groupe_dose)
sample_metadata_allv2_v4$Groupe_dose = relevel(sample_metadata_allv2_v4$Groupe_dose, ref = "CP.1") 
save(sample_metadata_allv2_v4, file="~/tolerance/data/sample_metadata_allv2_v4.rda")
load("~/tolerance/data/sample_metadata_allv2_v4.rda")

load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allv2_v4 = genus_tmp[match(sample_metadata_allv2_v4$samplenr, colnames(genus_tmp))]
genus_dose_allv2_v4$genus= rownames(genus_dose_allv2_v4)
genus= genus_dose_allv2_v4
save(genus, file="~/tolerance/data/genus_dose_allv2_v4.rda")
load("~/tolerance/data/genus_dose_allv2_v4.rda")

```


```{r}

genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allv2_v4 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
  
```


## global time effect
```{r}

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allv2_v4$samplenr,]), 
  colData = Tolerance::sample_metadata_allv2_v4 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)
save(dds_res1, file="deseq2_dds_res1_analysis_allv2v4.rda")

```

## product effect
```{r}

temp <- Tolerance::sample_metadata_allv2_v4 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.1") 



# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

save(dds2_res1, file="deseq2_dds2_res1_analysis_16S_336samples_4groups.rda")

results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# !!!! Lactobacillus : 236.112249      -2.613678 0.5985297 31.66544 1.558094e-03 0.0161100151

results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
#  !!!!!! Lactobacillus   236.112249    1.400013855 0.8311945 31.66544 1.558094e-03 1.611002e-02

results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
 #  !!!!!! Lactobacillus  236.112249     3.17274985 0.8363703 31.66544 1.558094e-03 1.611002e-02

results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
 #  !!!!!! Lactobacillus  236.112249     2.68523368 0.8465163 31.66544 1.558094e-03 1.611002e-02
  
results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV3","Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
 #  !!!!!! Lactobacillus  236.112249    0.863174913 0.8232554 31.66544 1.558094e-03 1.611002e-02

results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
#  !!!!!! Lactobacillus  236.112249      0.4587968 0.8230559 31.66544 1.558094e-03 1.611002e-02



dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# 0 genres

results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 
# Lactobacillus 2.361122e+02    1.400013855  0.8311945  1.68433971 0.0921160347 0.56107039


```


# selection des samples uniquement au temps V2 et V4 à partir des 336 samples (qui avaient au min v2 et v4 parmi les 4 visites)
```{r}

sample_metadata_allv2_v4 = read.csv2("~/tolerance/data/sample_metadata_allv2_v4.csv")
sample_metadata_allv2_v4 = sample_metadata_allv2_v4[sample_metadata_allv2_v4$v2_v4=="1",]
#336 samples (instead of 349)

sample_metadata_allv2_v4selectv2v4 = sample_metadata_allv2_v4[sample_metadata_allv2_v4$Visit=="V2" | sample_metadata_allv2_v4$Visit=="V4",]
# 170 samples

sample_metadata_allv2_v4selectv2v4$samplenr = as.character(sample_metadata_allv2_v4selectv2v4$samplenr)
sample_metadata_allv2_v4selectv2v4$Subject = as.character(sample_metadata_allv2_v4selectv2v4$Subject)
sample_metadata_allv2_v4selectv2v4$Groupe_dose = as.factor(sample_metadata_allv2_v4selectv2v4$Groupe_dose)
sample_metadata_allv2_v4selectv2v4$Groupe_dose = relevel(sample_metadata_allv2_v4selectv2v4$Groupe_dose, ref = "CP.1") 
sample_metadata_allv2_v4selectv2v4$Groupe = as.factor(sample_metadata_allv2_v4selectv2v4$Groupe)
sample_metadata_allv2_v4selectv2v4$Groupe = relevel(sample_metadata_allv2_v4selectv2v4$Groupe, ref = "CP") 
save(sample_metadata_allv2_v4selectv2v4, file="~/tolerance/data/sample_metadata_allv2_v4selectv2v4.rda")
load("~/tolerance/data/sample_metadata_allv2_v4selectv2v4.rda")

load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allv2_v4selectv2v4 = genus_tmp[match(sample_metadata_allv2_v4selectv2v4$samplenr, colnames(genus_tmp))]
genus_dose_allv2_v4selectv2v4$genus= rownames(genus_dose_allv2_v4selectv2v4)
genus= genus_dose_allv2_v4selectv2v4
save(genus, file="~/tolerance/data/genus_dose_allv2_v4selectv2v4.rda")
load("~/tolerance/data/genus_dose_allv2_v4selectv2v4.rda")


genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allv2_v4selectv2v4 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head





dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allv2_v4selectv2v4$samplenr,]), 
  colData = Tolerance::sample_metadata_allv2_v4selectv2v4 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# Lacto ressort pas !



temp <- Tolerance::sample_metadata_allv2_v4selectv2v4 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe = as.factor(temp$Groupe)
temp$Groupe = relevel(temp$Groupe, ref = "CP") 

dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe:subject.n + Groupe + Groupe:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe:subject.n + Groupe, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)


results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# !!!! Lactobacillus : 230.565194       3.011542 0.3936582  40.169191 1.893961e-09 3.463243e-08
# !!!! Streptococcus 499.606872       1.017087 0.2924239   8.936449 1.146766e-02 5.871440e-02

results(dds2_res1, contrast = list("GroupeATN.VisitV4","GroupeCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# !!!! Lactobacillus : 230.565194    1.848606318 0.5486056  40.16919 1.893961e-09 3.463243e-08

dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

results(dds2_res2, contrast = list("GroupeATN.VisitV4","GroupeCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# 0 genres !
# !!!! Lactobacillus : 2.305652e+02    1.848606318 0.5486056  3.369645540 0.0007526493 0.09633911
```

# selection des samples uniquement au temps V2 et V4 et de la dose 3 à partir des 336 samples (qui avaient au min v2 et v4 parmi les 4 visites)

```{r}
sample_metadata_allv2_v4 = read.csv2("~/tolerance/data/sample_metadata_allv2_v4.csv")
sample_metadata_allv2_v4 = sample_metadata_allv2_v4[sample_metadata_allv2_v4$v2_v4=="1",]
#336 samples (instead of 349)

sample_metadata_allv2_v4selectv2v4 = sample_metadata_allv2_v4[sample_metadata_allv2_v4$Visit=="V2" | sample_metadata_allv2_v4$Visit=="V4",]
# 170 samples

sample_metadata_allv2_v4selectv2v4_dose3 = sample_metadata_allv2_v4selectv2v4[sample_metadata_allv2_v4selectv2v4$Doses=="3",]
# 84 samples

sample_metadata_allv2_v4selectv2v4_dose3$samplenr = as.character(sample_metadata_allv2_v4selectv2v4_dose3$samplenr)

sample_metadata_allv2_v4selectv2v4_dose3$Subject = as.character(sample_metadata_allv2_v4selectv2v4_dose3$Subject)

sample_metadata_allv2_v4selectv2v4_dose3$Groupe_dose = as.factor(sample_metadata_allv2_v4selectv2v4_dose3$Groupe_dose)

sample_metadata_allv2_v4selectv2v4_dose3$Groupe_dose = relevel(sample_metadata_allv2_v4selectv2v4_dose3$Groupe_dose, ref = "CP.1") 

sample_metadata_allv2_v4selectv2v4_dose3$Groupe = as.factor(sample_metadata_allv2_v4selectv2v4_dose3$Groupe)
sample_metadata_allv2_v4selectv2v4_dose3$Groupe = relevel(sample_metadata_allv2_v4selectv2v4_dose3$Groupe, ref = "CP") 
save(sample_metadata_allv2_v4selectv2v4_dose3, file="~/tolerance/data/sample_metadata_allv2_v4selectv2v4_dose3.rda")
load("~/tolerance/data/sample_metadata_allv2_v4selectv2v4_dose3.rda")

load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allv2_v4selectv2v4_dose3 = genus_tmp[match(sample_metadata_allv2_v4selectv2v4_dose3$samplenr, colnames(genus_tmp))]
genus_dose_allv2_v4selectv2v4_dose3$genus= rownames(genus_dose_allv2_v4selectv2v4_dose3)
genus= genus_dose_allv2_v4selectv2v4_dose3
save(genus, file="~/tolerance/data/genus_dose_allv2_v4selectv2v4_dose3.rda")
load("~/tolerance/data/genus_dose_allv2_v4selectv2v4_dose3.rda")


genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allv2_v4selectv2v4_dose3 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head





dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allv2_v4selectv2v4_dose3$samplenr,]), 
  colData = Tolerance::sample_metadata_allv2_v4selectv2v4_dose3 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# Lactobacillus :  186.95751       3.208547 1.8841478 25.059571 5.558617e-07 1.156192e-05



temp <- Tolerance::sample_metadata_allv2_v4selectv2v4_dose3 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe = as.factor(temp$Groupe)
temp$Groupe = relevel(temp$Groupe, ref = "CP") 

dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe:subject.n + Groupe + Groupe:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe:subject.n + Groupe, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)


results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# Lactobacillus 177.738874       3.682897 0.6156480  26.705952 1.588094e-06 3.303236e-05



results(dds2_res1, contrast = list("GroupeATN.VisitV4","GroupeCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# !!!! Lactobacillus :  177.738874     1.72387043 0.8406082  26.705952 1.588094e-06 3.303236e-05

dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

results(dds2_res2, contrast = list("GroupeATN.VisitV4","GroupeCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# 0 genres !

results(dds2_res2, contrast = list("GroupeATN.VisitV4","GroupeCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")
# !!!! Lactobacillus : 177.738874    1.723870433 0.8406082  2.050741863 0.040292092 0.7612292
```
