---
title: "Differential analysis"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}



```



```{r}

load("genus.rda")

Tolerance::sample_metadata %>% head

sample_metadata$Groupe = as.factor(sample_metadata$Groupe)
str(sample_metadata$Groupe)
sample_metadata$Groupe = relevel(sample_metadata$Groupe, ref = "CP") 
# > str(sample_metadata$Groupe)
#  Factor w/ 2 levels "CP","ATN": 1 2 2 1 2 2 2 1 2 1 ...
sample_metadata$Groupe_dose = as.factor(sample_metadata$Groupe_dose)
sample_metadata$Groupe_dose = relevel(sample_metadata$Groupe_dose, ref = "CP.1") 


```


## Filter abundant taxa
```{r}

genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select



genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata %>%
  tibble::column_to_rownames("samplenr") %>% head
  


```

## global time effect
```{r}


dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[sample_metadata$samplenr,]), 
  colData = sample_metadata %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)



dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)




save(dds_res1, file="deseq2_dds_res1_analysis.rda")

```




```{r}

results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)



```



```{r}
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  #filter(padj<0.05) %>%
  arrange(padj) %>%
  ggplot() + geom_point(aes(x=baseMean,y=log2FoldChange,color=padj<0.05)) + scale_x_log10()

```



## Specific group effect and visit




```{r}


# temp <- Tolerance::sample_metadata #%>% tibble::column_to_rownames("samplenr")
temp <- sample_metadata #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.1") 

temp$Groupe = as.factor(temp$Groupe)
temp$Groupe = relevel(temp$Groupe, ref = "CP") 


# DESeq2 object and design matrices


dds3 <- dds
# dds2 <-  DESeq2::DESeqDataSetFromMatrix(
#   countData = t(genus_count[sample_metadata$samplenr,]),
#   # colData = sample_metadata %>% tibble::column_to_rownames("samplenr"),
#   colData = sample_metadata,
#   design = ~ 1)

# dds2 <- estimateSizeFactors(dds2, type="poscounts")
dds3 <- estimateSizeFactors(dds3, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
# dds2 <- estimateDispersions(dds2, modelMatrix = mod)
dds3 <- estimateDispersions(dds3, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


# dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)
dds3_res1 <- nbinomLRT(dds3, full = mod, reduced = mod2)

idx_lactob<-grep("Lactobacillus", res_dds2$genus)

## Verifie la convergence de Bifid
mcols(dds2_res1)[40, "fullBetaConv"]
# TRUE

# using supplied model matrix
#67 rows did not converge in beta, labelled in mcols(object)$fullBetaConv. Use larger maxit argument with nbinomLRT

save(dds2_res1, file="deseq2_dds2_res1_analysis.rda")

results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)



# dds = DESeq2::DESeqDataSetFromMatrix(
#   countData = t(genus_count[temp$samplenr,]), 
#   colData = Tolerance::sample_metadata %>% tibble::column_to_rownames("samplenr"), 
#   design = ~ Visit + Subject)





```



```{r}

# Group comparisons at each time point
dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

#using supplied model matrix
#67 rows did not converge in beta, labelled in mcols(object)$betaConv. Use larger maxit argument with nbinomWaldTest

DESeq2::resultsNames(dds2_res2)
#   [1] "Intercept"                     "Groupe_doseATN.1"             
#   [3] "Groupe_doseATN.3"              "Groupe_doseCP.3"              
#   [5] "Groupe_doseCP.1.subject.nS10"  "Groupe_doseATN.1.subject.nS10"
#   [7] "Groupe_doseATN.3.subject.nS10" "Groupe_doseCP.3.subject.nS10" 
#   [9] "Groupe_doseCP.1.subject.nS11"  "Groupe_doseATN.1.subject.nS11"
#  [11] "Groupe_doseATN.3.subject.nS11" "Groupe_doseCP.3.subject.nS11" 
#  [13] "Groupe_doseCP.1.subject.nS12"  "Groupe_doseATN.1.subject.nS12"
#  [15] "Groupe_doseATN.3.subject.nS12" "Groupe_doseCP.3.subject.nS12" 
#  [17] "Groupe_doseCP.1.subject.nS13"  "Groupe_doseATN.1.subject.nS13"
#  [19] "Groupe_doseATN.3.subject.nS13" "Groupe_doseCP.3.subject.nS13" 
#  [21] "Groupe_doseCP.1.subject.nS14"  "Groupe_doseATN.1.subject.nS14"
#  [23] "Groupe_doseATN.3.subject.nS14" "Groupe_doseCP.3.subject.nS14" 
#  [25] "Groupe_doseCP.1.subject.nS15"  "Groupe_doseATN.1.subject.nS15"
#  [27] "Groupe_doseATN.3.subject.nS15" "Groupe_doseCP.3.subject.nS15" 
#  [29] "Groupe_doseCP.1.subject.nS16"  "Groupe_doseATN.1.subject.nS16"
#  [31] "Groupe_doseATN.3.subject.nS16" "Groupe_doseCP.3.subject.nS16" 
#  [33] "Groupe_doseCP.1.subject.nS17"  "Groupe_doseATN.1.subject.nS17"
#  [35] "Groupe_doseATN.3.subject.nS17" "Groupe_doseCP.3.subject.nS17" 
#  [37] "Groupe_doseCP.1.subject.nS18"  "Groupe_doseATN.1.subject.nS18"
#  [39] "Groupe_doseATN.3.subject.nS18" "Groupe_doseCP.3.subject.nS18" 
#  [41] "Groupe_doseCP.1.subject.nS19"  "Groupe_doseATN.1.subject.nS19"
#  [43] "Groupe_doseATN.3.subject.nS19" "Groupe_doseCP.3.subject.nS19" 
#  [45] "Groupe_doseCP.1.subject.nS2"   "Groupe_doseATN.1.subject.nS2" 
#  [47] "Groupe_doseATN.3.subject.nS2"  "Groupe_doseCP.3.subject.nS2"  
#  [49] "Groupe_doseCP.1.subject.nS20"  "Groupe_doseATN.1.subject.nS20"
#  [51] "Groupe_doseATN.3.subject.nS20" "Groupe_doseCP.3.subject.nS20" 
#  [53] "Groupe_doseCP.1.subject.nS21"  "Groupe_doseATN.1.subject.nS21"
#  [55] "Groupe_doseATN.3.subject.nS21" "Groupe_doseCP.3.subject.nS21" 
#  [57] "Groupe_doseATN.1.subject.nS22" "Groupe_doseATN.3.subject.nS22"
#  [59] "Groupe_doseCP.3.subject.nS22"  "Groupe_doseCP.1.subject.nS3"  
#  [61] "Groupe_doseATN.1.subject.nS3"  "Groupe_doseATN.3.subject.nS3" 
#  [63] "Groupe_doseCP.3.subject.nS3"   "Groupe_doseCP.1.subject.nS4"  
#  [65] "Groupe_doseATN.1.subject.nS4"  "Groupe_doseATN.3.subject.nS4" 
#  [67] "Groupe_doseCP.3.subject.nS4"   "Groupe_doseCP.1.subject.nS5"  
#  [69] "Groupe_doseATN.1.subject.nS5"  "Groupe_doseATN.3.subject.nS5" 
#  [71] "Groupe_doseCP.3.subject.nS5"   "Groupe_doseCP.1.subject.nS6"  
#  [73] "Groupe_doseATN.1.subject.nS6"  "Groupe_doseATN.3.subject.nS6" 
#  [75] "Groupe_doseCP.3.subject.nS6"   "Groupe_doseCP.1.subject.nS7"  
#  [77] "Groupe_doseATN.1.subject.nS7"  "Groupe_doseATN.3.subject.nS7" 
#  [79] "Groupe_doseCP.3.subject.nS7"   "Groupe_doseCP.1.subject.nS8"  
#  [81] "Groupe_doseATN.1.subject.nS8"  "Groupe_doseATN.3.subject.nS8" 
#  [83] "Groupe_doseCP.3.subject.nS8"   "Groupe_doseCP.1.subject.nS9"  
#  [85] "Groupe_doseATN.1.subject.nS9"  "Groupe_doseATN.3.subject.nS9" 
#  [87] "Groupe_doseCP.3.subject.nS9"   "Groupe_doseATN.3.subject.nS23"
#  [89] "Groupe_doseCP.3.subject.nS23"  "Groupe_doseCP.3.subject.nS24" 
#  [91] "Groupe_doseCP.1.VisitV3"       "Groupe_doseATN.1.VisitV3"     
#  [93] "Groupe_doseATN.3.VisitV3"      "Groupe_doseCP.3.VisitV3"      
#  [95] "Groupe_doseCP.1.VisitV4"       "Groupe_doseATN.1.VisitV4"     
#  [97] "Groupe_doseATN.3.VisitV4"      "Groupe_doseCP.3.VisitV4"      
#  [99] "Groupe_doseCP.1.VisitV5"       "Groupe_doseATN.1.VisitV5"     
# [101] "Groupe_doseATN.3.VisitV5"      "Groupe_doseCP.3.VisitV5"    


DESeq2::resultsNames(dds2_res2)[grep("ATN.1",DESeq2::resultsNames(dds2_res2))]

save(dds2_res2, file="deseq2_dds2_res2_analysis.rda" )


```



```{r}

tmp_data_plot<-counts(dds2, normalized=TRUE)[idx_lactob, ] %>% as.data.frame %>% tibble::rownames_to_column() %>% dplyr::rename(samplenr=rowname) %>% full_join(., sample_metadata, by="samplenr")
colnames(tmp_data_plot)[2]<-"Lactobacillus"


ggplot(tmp_data_plot, aes(x=Groupe_dose, y=Lactobacillus))+geom_boxplot()+facet_wrap(~Visit)+scale_y_log10()


```


```{r}

## Effet temps ATN --------------

# ATN3 Vs baseline
res_ATN3_v2v3= 
  results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3", "Groupe_doseATN.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_v2v3, file="res_ATN3_v2v3_p0.05.rda")

res_ATN3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4", "Groupe_doseATN.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_v2v4, file="res_ATN3_v2v4_p0.05.rda")

res_ATN3_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5", "Groupe_doseATN.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_v2v5, file="res_ATN3_v2v5_p0.05.rda")


# ATN1 Vs baseline

res_ATN1_v2v3= 
  results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV3","Groupe_doseATN.1"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_v2v3, file="res_ATN1_v2v3_p0.05.rda")

res_ATN1_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseATN.1"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_v2v4, file="res_ATN1_v2v4_p0.05.rda")

res_ATN1_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV5","Groupe_doseATN.1"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_v2v5, file="res_ATN1_v2v5_p0.05.rda")


## Effet dose ATN --------------

# ATN3 vs ATN1 by Visit

res_ATN3_ATN1_v2=
results(dds2_res2, contrast = list("Groupe_doseATN.3", "Groupe_doseATN.1"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_ATN1_v2, file="res_ATN3_ATN1_v2_p0.05.rda")

res_ATN3_ATN1_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseATN.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_ATN1_v2v3, file="res_ATN3_ATN1_v2v3_p0.05.rda")

res_ATN3_ATN1_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseATN.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_ATN1_v2v4, file="res_ATN3_ATN1_v2v4_p0.05.rda")

res_ATN3_ATN1_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseATN.1.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_ATN1_v2v5, file="res_ATN3_ATN1_v2v5_p0.05.rda")


## Dose - groupe --------------

# ATN1 vs CP1 by Visit

res_ATN1_CP1_v2=
  results(dds2_res2, contrast = list("Groupe_doseATN.1"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2, file="res_ATN1_CP1_v2_p0.05.rda")

res_ATN1_CP1_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV3","Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v3, file="res_ATN1_CP1_v2v3_p0.05.rda")

res_ATN1_CP1_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v4, file="res_ATN1_CP1_v2v4_p0.05.rda")

res_ATN1_CP1_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV5","Groupe_doseCP.1.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v5, file="res_ATN1_CP1_v2v5_p0.05.rda")


# ATN3 vs CP3 by Visit

res_ATN3_CP3_v2=
results(dds2_res2, contrast = list("Groupe_doseATN.3","Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2, file="res_ATN3_CP3_v2_p0.05.rda")

res_ATN3_CP3_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05.rda")

res_ATN3_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05.rda")

res_ATN3_CP3_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v5, file="res_ATN3_CP3_v2v5_p0.05.rda")


## Effet temps CP  --------------


# CP3 Vs baseline
res_CP3_v2v3= 
  results(dds2_res2, contrast = list("Groupe_doseCP.3.VisitV3", "Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP3_v2v3, file="res_CP3_v2v3_p0.05.rda")

res_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseCP.3.VisitV4", "Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP3_v2v4, file="res_CP3_v2v4_p0.05.rda")

res_CP3_v2v5=
results(dds2_res2, contrast = list("Groupe_doseCP.3.VisitV5", "Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP3_v2v5, file="res_CP3_v2v5_p0.05.rda")


# CP1 Vs baseline

res_CP1_v2v3= 
  results(dds2_res2, contrast = list("Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP1_v2v3, file="res_CP1_v2v3_p0.05.rda")

res_CP1_v2v4=
results(dds2_res2, contrast = list("Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP1_v2v4, file="res_CP1_v2v4_p0.05.rda")

res_CP1_v2v5=
results(dds2_res2, contrast = list("Groupe_doseCP.1.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP1_v2v5, file="res_CP1_v2v5_p0.05.rda")



## Effet dose CP  --------------

# CP3 vs CP1 by Visit

res_CP3_CP1_v2=
results(dds2_res2, contrast = list("Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP3_CP1_v2, file="res_CP3_CP1_v2_p0.05.rda")

res_CP3_CP1_v2v3=
results(dds2_res2, contrast = list("Groupe_doseCP.3.VisitV3","Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP3_CP1_v2v3, file="res_CP3_CP1_v2v3_p0.05.rda")

res_CP3_CP1_v2v4=
results(dds2_res2, contrast = list("Groupe_doseCP.3.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP3_CP1_v2v4, file="res_CP3_CP1_v2v4_p0.05.rda")

res_CP3_CP1_v2v5=
results(dds2_res2, contrast = list("Groupe_doseCP.3.VisitV5","Groupe_doseCP.1.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_CP3_CP1_v2v5, file="res_CP3_CP1_v2v5_p0.05.rda")




```


```{r}
## Travail sur Lactobacillus pour essayer d'expliquer pourquoi pas significatif à V4 entre ATN3 et CP3 comme attendu par MFH

save(dds3, temp, file="./data/export_local.RData")

normCounts<-counts(dds3, normalized=T)
## => suite realisee en local sur mon PC car pbl de library R sur le serveur a ce moment


##################



## Essai de retirer le sujet 276001054 car il a ete identifie comme ayant une forte valeur de LactoB a baseline (et c'est un Control) donc cela peut biaiser la normalisation


# sample ID associes au sujet 276001054
id_276001054<-sample_metadata$samplenr[sample_metadata$Subject == "276001054"]

# Nettoyage de la table des comptages
genus_count_2<-genus_count[!rownames(genus_count) %in% id_276001054, ]

# Nettoyade des metadonnes
temp_2<-sample_metadata[!sample_metadata$samplenr %in% id_276001054, ]

temp_2 <- temp_2 #%>% tibble::column_to_rownames("samplenr")
temp_2 <- temp_2[with(temp_2, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp_2), 
                                temp_2$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp_2 = full_join(temp_2, 
                  new_sub, 
                  by = "Subject")
rownames(temp_2) <- temp_2$samplenr

temp_2 # need here to force level factor

temp_2$Groupe_dose = as.factor(temp_2$Groupe_dose)
temp_2$Groupe_dose = relevel(temp_2$Groupe_dose, ref = "CP.1") 

temp_2$Groupe = as.factor(temp_2$Groupe)
temp_2$Groupe = relevel(temp_2$Groupe, ref = "CP") 

# Mise en ordre des 2 tables
rownames(temp_2)<-temp_2$samplenr
temp_2<-data.frame(temp_2)
temp_2<-temp_2[rownames(genus_count_2), ]



dds_test1 = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count_2[temp_2$samplenr,]), 
  colData = temp_2, 
  design = ~ Visit + Subject)

# Estimate Size Factor
dds_test1 <- estimateSizeFactors(dds_test1, type="poscounts")

# Full design matrix
mod_test1 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp_2)
mod_test1 <- mod_test1[,colSums(mod_test1)>0]

# Estimate Dispersion
dds_test1 <- estimateDispersions(dds_test1, modelMatrix = mod_test1)


## Verification de la normalisation
normCounts_test1<-counts(dds_test1, normalized=T)

## Correlation entre comptages brutes et comptages normalises
idx_lactobNorm<-grep("Lactobacillus", rownames(normCounts_test1))
# set1 - ATN3 et CP3 a V2 et V4
idx_set1<-temp_2 %>% filter(Visit %in% c("V2", "V4")) %>% filter(Groupe_dose %in% c("ATN.3", "CP.3")) %>% dplyr::select(samplenr) %>% c()

lactoB_set1<-data.frame(Lactobacillus=normCounts_test1[idx_lactobNorm, idx_set1[[1]]])
lactoB_set1$samplenr<-rownames(lactoB_set1)
lactoB_set1<-merge(lactoB_set1, temp_2, by="samplenr")

idx_lactobRaw<-grep("Lactobacillus", genus$genus)
lactoB_set1_raw<-as(genus[idx_lactobRaw, idx_set1[[1]]], "numeric")
names(lactoB_set1_raw)<-idx_set1[[1]]
lactoB_set1_norm<-normCounts_test1[idx_lactobNorm, idx_set1[[1]]]

# all(names(lactoB_set1_raw) == names(lactoB_set1_norm)) # => OK, meme ordre

plot(lactoB_set1_norm, lactoB_set1_raw)
# => par rapport aux donnes avec le sujet 276001054, il y a du mieux car plus de point extreme




# Reduced design matrix
mod2_test1 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp_2)
mod2_test1 = mod2_test1[, colSums(mod2_test1)>0]

dds_test1_res1 <- nbinomLRT(dds_test1, full = mod_test1, reduced = mod2_test1)

dds_test1_resWald = nbinomWaldTest(dds_test1, modelMatrix = mod_test1, betaPrior = FALSE)

save(dds_test1_resWald, file="/data/dds_test1_resWald.rda")


# ATN3 vs CP3 by Visit

restest1_ATN3_CP3_v2=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3","Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")

restest1_ATN3_CP3_v2v3=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")

restest1_ATN3_CP3_v2v4=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")

restest1_ATN3_CP3_v2v5=
results(dds_test1_resWald, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")



```
