---
title: "Differential analysis pool CP"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}

```


```{r}

load("genus.rda")

Tolerance::sample_metadata %>% head

sample_metadata$Groupe = as.factor(sample_metadata$Groupe)
str(sample_metadata$Groupe)
sample_metadata$Groupe = relevel(sample_metadata$Groupe, ref = "CP") 
# > str(sample_metadata$Groupe)
#  Factor w/ 2 levels "CP","ATN": 1 2 2 1 2 2 2 1 2 1 ...
sample_metadata$Groupe_dose = as.factor(sample_metadata$Groupe_dose)
sample_metadata$Groupe_dose = relevel(sample_metadata$Groupe_dose, ref = "CP.1") 

```

```{r}

 sample_metadata %>% head

 sample_metadata$fx = sample_metadata$Groupe_dose 
 sample_metadata %>%
  mutate(fx = fx %>% gsub("CP.1","CP",.)) %>%
  mutate(fx = fx %>% gsub("CP.3","CP",.)) -> sample_metadata_pool_CP
 
sample_metadata_pool_CP %>% head
sample_metadata_pool_CP$fx = as.factor(sample_metadata_pool_CP$fx)
sample_metadata_pool_CP$fx = relevel(sample_metadata_pool_CP$fx, ref = "CP") 

save(sample_metadata_pool_CP, file="/home/alvareao/tolerance/data/sample_metadata_pool_CP.rda")

```


```{r}
genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select

genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_pool_CP %>%
  tibble::column_to_rownames("samplenr") %>% head


```


```{r}


dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_pool_CP$samplenr,]), 
  colData = Tolerance::sample_metadata_pool_CP %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)
# converting counts to integer mode
# some variables in design formula are characters, converting to factors> 

# sample_metadata_pool_CP$Visit = as.factor(sample_metadata_pool_CP$Visit)
# sample_metadata_pool_CP$Subject = as.factor(sample_metadata_pool_CP$Subject)
# sample_metadata_pool_CP$samplenr = as.factor(sample_metadata_pool_CP$samplenr)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

save(dds_res1, file="deseq2_dds_res1_analysis_pool_CP.rda")




temp <- Tolerance::sample_metadata_pool_CP  #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(fx, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$fx, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr


# Column `Subject` joining character vector and factor, coercing into character vector
# > rownames(temp) <- temp$samplenr
# Setting row names on a tibble is deprecated.> 

temp # need here to force level factor

temp$fx = as.factor(temp$fx)
temp$fx = relevel(temp$fx, ref = "CP") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ fx:subject.n + fx + fx:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ fx:subject.n + fx, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

# using supplied model matrix
# 12 rows did not converge in beta, labelled in mcols(object)$fullBetaConv. Use larger maxit argument with nbinomLRT

save(dds2_res1, file="deseq2_dds2_res1_analysis_pool_CP.rda")


dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)


DESeq2::resultsNames(dds2_res2)

#  [1] "Intercept"            "fxATN.1"              "fxATN.3"              "fxCP.subject.nS10"   
#  [5] "fxATN.1.subject.nS10" "fxATN.3.subject.nS10" "fxCP.subject.nS11"    "fxATN.1.subject.nS11"
#  [9] "fxATN.3.subject.nS11" "fxCP.subject.nS12"    "fxATN.1.subject.nS12" "fxATN.3.subject.nS12"
# [13] "fxCP.subject.nS13"    "fxATN.1.subject.nS13" "fxATN.3.subject.nS13" "fxCP.subject.nS14"   
# [17] "fxATN.1.subject.nS14" "fxATN.3.subject.nS14" "fxCP.subject.nS15"    "fxATN.1.subject.nS15"
# [21] "fxATN.3.subject.nS15" "fxCP.subject.nS16"    "fxATN.1.subject.nS16" "fxATN.3.subject.nS16"
# [25] "fxCP.subject.nS17"    "fxATN.1.subject.nS17" "fxATN.3.subject.nS17" "fxCP.subject.nS18"   
# [29] "fxATN.1.subject.nS18" "fxATN.3.subject.nS18" "fxCP.subject.nS19"    "fxATN.1.subject.nS19"
# [33] "fxATN.3.subject.nS19" "fxCP.subject.nS2"     "fxATN.1.subject.nS2"  "fxATN.3.subject.nS2" 
# [37] "fxCP.subject.nS20"    "fxATN.1.subject.nS20" "fxATN.3.subject.nS20" "fxCP.subject.nS21"   
# [41] "fxATN.1.subject.nS21" "fxATN.3.subject.nS21" "fxCP.subject.nS22"    "fxATN.1.subject.nS22"
# [45] "fxATN.3.subject.nS22" "fxCP.subject.nS23"    "fxATN.3.subject.nS23" "fxCP.subject.nS24"   
# [49] "fxCP.subject.nS25"    "fxCP.subject.nS26"    "fxCP.subject.nS27"    "fxCP.subject.nS28"   
# [53] "fxCP.subject.nS29"    "fxCP.subject.nS3"     "fxATN.1.subject.nS3"  "fxATN.3.subject.nS3" 
# [57] "fxCP.subject.nS30"    "fxCP.subject.nS31"    "fxCP.subject.nS32"    "fxCP.subject.nS33"   
# [61] "fxCP.subject.nS34"    "fxCP.subject.nS35"    "fxCP.subject.nS36"    "fxCP.subject.nS37"   
# [65] "fxCP.subject.nS38"    "fxCP.subject.nS39"    "fxCP.subject.nS4"     "fxATN.1.subject.nS4" 
# [69] "fxATN.3.subject.nS4"  "fxCP.subject.nS40"    "fxCP.subject.nS41"    "fxCP.subject.nS42"   
# [73] "fxCP.subject.nS43"    "fxCP.subject.nS44"    "fxCP.subject.nS45"    "fxCP.subject.nS5"    
# [77] "fxATN.1.subject.nS5"  "fxATN.3.subject.nS5"  "fxCP.subject.nS6"     "fxATN.1.subject.nS6" 
# [81] "fxATN.3.subject.nS6"  "fxCP.subject.nS7"     "fxATN.1.subject.nS7"  "fxATN.3.subject.nS7" 
# [85] "fxCP.subject.nS8"     "fxATN.1.subject.nS8"  "fxATN.3.subject.nS8"  "fxCP.subject.nS9"    
# [89] "fxATN.1.subject.nS9"  "fxATN.3.subject.nS9"  "fxCP.VisitV3"         "fxATN.1.VisitV3"     
# [93] "fxATN.3.VisitV3"      "fxCP.VisitV4"         "fxATN.1.VisitV4"      "fxATN.3.VisitV4"     
# [97] "fxCP.VisitV5"         "fxATN.1.VisitV5"      "fxATN.3.VisitV5"     


save(dds2_res2, file="deseq2_dds2_res2_analysis_pool_CP.rda" )

```

```{r}

## Dose - groupe --------------

# ATN1 vs CP1 by Visit

res_ATN1_CP1_v2_poolCP=
  results(dds2_res2, contrast = list("fxATN.1"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2_poolCP, file="res_ATN1_CP1_v2_p0.05_poolCP.rda")

res_ATN1_CP1_v2v3_poolCP=
results(dds2_res2, contrast = list("fxATN.1.VisitV3","fxCP.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v3_poolCP, file="res_ATN1_CP1_v2v3_p0.05_poolCP.rda")

res_ATN1_CP1_v2v4_poolCP=
results(dds2_res2, contrast = list("fxATN.1.VisitV4","fxCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v4_poolCP, file="res_ATN1_CP1_v2v4_p0.05_poolCP.rda")

res_ATN1_CP1_v2v5_poolCP=
results(dds2_res2, contrast = list("fxATN.1.VisitV5","fxCP.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v5_poolCP, file="res_ATN1_CP1_v2v5_p0.05_poolCP.rda")


# ATN3 vs CP3 by Visit

res_ATN3_CP3_v2_poolCP=
results(dds2_res2, contrast = list("fxATN.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2_poolCP, file="res_ATN3_CP3_v2_p0.05_poolCP.rda")

res_ATN3_CP3_v2v3_poolCP=
results(dds2_res2, contrast = list("fxATN.3.VisitV3","fxCP.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v3_poolCP, file="res_ATN3_CP3_v2v3_p0.05_poolCP.rda")

res_ATN3_CP3_v2v4_poolCP=
results(dds2_res2, contrast = list("fxATN.3.VisitV4","fxCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4_poolCP, file="res_ATN3_CP3_v2v4_p0.05_poolCP.rda")

res_ATN3_CP3_v2v5_poolCP=
results(dds2_res2, contrast = list("fxATN.3.VisitV5","fxCP.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v5_poolCP, file="res_ATN3_CP3_v2v5_p0.05_poolCP.rda")


```

```{r}

tiff(file="DESeq2_ATN3_CP3_analysis_noDO_pool_CP.tiff", w=1500, h=500) 
rbind(
    data.frame(res_ATN3_CP3_v2v3_poolCP,visit="D14"),
    data.frame(res_ATN3_CP3_v2v4_poolCP,visit="D28"), 
    data.frame(res_ATN3_CP3_v2v5_poolCP,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()



tiff(file="DESeq2_ATN1_CP1_analysis_noDO_pool_CP.tiff", w=1500, h=500) 
rbind(
    data.frame(res_ATN1_CP1_v2v3_poolCP,visit="D14"),
    data.frame(res_ATN1_CP1_v2v4_poolCP,visit="D28")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()




```

