---
title: "Differential analysis"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}

```

### test en mettant la variable visit en facteur

```{r}

load("genus.rda")

Tolerance::sample_metadata %>% head

sample_metadata$Groupe = as.factor(sample_metadata$Groupe)
sample_metadata$Visit = as.factor(sample_metadata$Visit)
sample_metadata$Groupe_dose = as.factor(sample_metadata$Groupe_dose)
sample_metadata$Doses = as.factor(sample_metadata$Doses)

str(sample_metadata)
sample_metadata$Groupe = relevel(sample_metadata$Groupe, ref = "CP")
sample_metadata$Groupe_dose = relevel(sample_metadata$Groupe_dose, ref = "CP.1")
# sample_metadata$Visit = relevel(sample_metadata$Visit, ref = "V2")


```


# Filter abundant taxa
```{r}

genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata %>%
  tibble::column_to_rownames("samplenr") %>% head
  
sample_metadata %>% head

```

```{r}

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata$samplenr,]), 
  colData = Tolerance::sample_metadata %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

# converting counts to integer mode
# some variables in design formula are characters, converting to factorsestimating size factors
# estimating dispersions
# gene-wise dispersion estimates
# mean-dispersion relationship
# final dispersion estimates
# fitting model and testing
# 19 rows did not converge in beta, labelled in mcols(object)$fullBetaConv. Use larger maxit argument with nbinomLRT
# 

results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)


temp <- Tolerance::sample_metadata #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.1") 

temp$Groupe = as.factor(temp$Groupe)
temp$Groupe = relevel(temp$Groupe, ref = "CP") 
temp$Visit = as.factor(temp$Visit)

dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)
# using supplied model matrix
# 70 rows did not converge in beta, labelled in mcols(object)$fullBetaConv. Use larger maxit argument with nbinomLRT


results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# Lactobacillus p=0.04, pajust = 0.78

dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)
# using supplied model matrix
# 70 rows did not converge in beta, labelled in mcols(object)$betaConv. Use larger maxit argument with nbinomWaldTest
# 
DESeq2::resultsNames(dds2_res2)


res_ATN3_CP3_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05.rda")

res_ATN3_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05.rda")

# plus de lactobacillus significatif

```

### test en mettant visit en reference


```{r}

load("genus.rda")

Tolerance::sample_metadata %>% head

sample_metadata$Groupe = as.factor(sample_metadata$Groupe)
sample_metadata$Visit = as.factor(sample_metadata$Visit)
sample_metadata$Groupe_dose = as.factor(sample_metadata$Groupe_dose)
sample_metadata$Doses = as.factor(sample_metadata$Doses)

str(sample_metadata)
# sample_metadata$Groupe = relevel(sample_metadata$Groupe, ref = "CP")
# sample_metadata$Groupe_dose = relevel(sample_metadata$Groupe_dose, ref = "CP.1")
sample_metadata$Visit = relevel(sample_metadata$Visit, ref = "V2")



genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata %>%
  tibble::column_to_rownames("samplenr") %>% head
  
sample_metadata %>% head

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata$samplenr,]), 
  colData = Tolerance::sample_metadata %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)



results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)


temp <- Tolerance::sample_metadata #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe = as.factor(temp$Groupe)
temp$Visit = as.factor(temp$Visit)
temp$Visit = relevel(temp$Visit, ref = "V2")


dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)


results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)



dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

 
DESeq2::resultsNames(dds2_res2)
# [1] "Intercept"                     "Groupe_doseATN.3"              "Groupe_doseCP.1"              
#   [4] "Groupe_doseCP.3"               "Groupe_doseATN.1.subject.nS10" "Groupe_doseATN.3.subject.nS10"

res_ATN3_CP3_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05.rda")

res_ATN3_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05.rda")



```



### test en prenant que la variable groupe : ATN vs CP


```{r}

load("genus.rda")

Tolerance::sample_metadata %>% head

sample_metadata$Groupe = as.factor(sample_metadata$Groupe)
sample_metadata$Visit = as.factor(sample_metadata$Visit)
sample_metadata$Groupe_dose = as.factor(sample_metadata$Groupe_dose)
sample_metadata$Doses = as.factor(sample_metadata$Doses)
sample_metadata$Groupe = relevel(sample_metadata$Groupe, ref = "CP")
# sample_metadata$Groupe_dose = relevel(sample_metadata$Groupe_dose, ref = "CP.1")
# sample_metadata$Visit = relevel(sample_metadata$Visit, ref = "V2")



genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata %>%
  tibble::column_to_rownames("samplenr") %>% head
  
sample_metadata %>% head

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata$samplenr,]), 
  colData = Tolerance::sample_metadata %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)

# converting counts to integer mode
# some variables in design formula are characters, converting to factors> 
  
dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)



results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)


temp <- Tolerance::sample_metadata #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe = as.factor(temp$Groupe)
temp$Visit = as.factor(temp$Visit)
temp$Groupe = relevel(temp$Groupe, ref = "CP")


dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe:subject.n + Groupe + Groupe:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe:subject.n + Groupe, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)


results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)



dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)
save(dds2_res2, file="dds2_res2_pool_ATN_CP.rda")
 
DESeq2::resultsNames(dds2_res2)

res_ATN_CP_v2v3=
results(dds2_res2, contrast = list("GroupeATN.VisitV3","GroupeCP.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN_CP_v2v3, file="res_ATN_CP_v2v3_p0.05_pool_CP_ATN.rda")

res_ATN_CP_v2v4=
results(dds2_res2, contrast = list("GroupeATN.VisitV4","GroupeCP.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN_CP_v2v4, file="res_ATN_CP_v2v4_p0.05_pool_CP_ATN.rda")

  # Lactobacillus ne ressort pas significatif

```



### test en prenant que ATN3 vs CP3 - v4

```{r}

sample_metadata_dose3v4 = sample_metadata[sample_metadata$Doses=="3" & sample_metadata$Visit=="V4",]
sample_metadata_dose3v4$Groupe = relevel(sample_metadata_dose3v4$Groupe, ref = "CP") 
sample_metadata_dose3v4$Groupe_dose = relevel(sample_metadata_dose3v4$Groupe_dose, ref = "CP.3") 
sample_metadata_dose3v4 %>% head
save(sample_metadata_dose3v4, file="../data/sample_metadata_dose3v4.rda")

load("genus.rda")
str(genus)
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose3v4 = genus_tmp[match(sample_metadata_dose3v4$samplenr, colnames(genus_tmp))]
genus_dose3v4$genus= rownames(genus_dose3v4)
genus= genus_dose3v4


Tolerance::sample_metadata %>% head

sample_metadata$Groupe = as.factor(sample_metadata$Groupe)
sample_metadata$Visit = as.factor(sample_metadata$Visit)
sample_metadata$Groupe_dose = as.factor(sample_metadata$Groupe_dose)
sample_metadata$Doses = as.factor(sample_metadata$Doses)




genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


sample_metadata_dose3v4 %>%
  tibble::column_to_rownames("samplenr") %>% head
  
sample_metadata_dose3v4 %>% head

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[sample_metadata_dose3v4$samplenr,]), 
  colData = sample_metadata_dose3v4 %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Groupe_dose)

# converting counts to integer mode
# factor levels were dropped which had no samples

dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")


temp <- sample_metadata_dose3v4 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe = as.factor(temp$Groupe)
temp$Visit = as.factor(temp$Visit)
temp$Groupe = relevel(temp$Groupe_dose, ref = "CP.3")


mod <- model.matrix(~ Groupe_dose , temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# error: inv(): matrix seems singular
# Error in fitDisp(ySEXP = ySEXP, xSEXP = xSEXP, mu_hatSEXP = mu_hatSEXP,  : 
#   inv(): matrix seems singular
  
  
# Reduced design matrix
#mod2 <- model.matrix(~ Groupe_dose:subject.n , temp)
#mod2 = mod2[, colSums(mod2)>0]


#dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

# Group comparisons at each time point
dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

#using supplied model matrix
#67 rows did not converge in beta, labelled in mcols(object)$betaConv. Use larger maxit argument with nbinomWaldTest

DESeq2::resultsNames(dds2_res2)

results(dds2_res2, alpha = 0.05) %>%
  data.frame() %>% tibble::rownames_to_column("genus") 



```
