---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}

```


## global time effect
```{r}

Tolerance::sample_metadata_metaG %>% head

sample_metadata_metaG_v2v4 = sample_metadata_metaG[sample_metadata_metaG$Visit=="V2" | sample_metadata_metaG$Visit=="V4",]
sample_metadata_metaG_v2v4 %>% head
sample_metadata_metaG_v2v4$Groupe_dose = as.factor(sample_metadata_metaG_v2v4$Groupe_dose)
sample_metadata_metaG_v2v4$Groupe_dose = relevel(sample_metadata_metaG_v2v4$Groupe_dose, ref = "CP.3") 
devtools::use_data(sample_metadata_metaG_v2v4, overwrite = TRUE)


data(MSP_abundance_matrix_rounded_5p)
#527 MSP

MSP_abundance_matrix_rounded_5p_v2v4 = MSP_abundance_matrix_rounded_5p[match(sample_metadata_metaG_v2v4$samplenr, colnames(MSP_abundance_matrix_rounded_5p))]

MSP_abundance_matrix_rounded_5p_v2v4$msp = rownames(MSP_abundance_matrix_rounded_5p_v2v4)
MSP_abundance_matrix_rounded_5p_v2v4 %>% head

MSP_abundance_matrix_rounded_5p_v2v4 %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("msp") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> MSP_select

MSP_abundance_matrix_rounded_5p_v2v4 = MSP_abundance_matrix_rounded_5p_v2v4[MSP_select,]
MSP_abundance_matrix_rounded_5p_v2v4 = MSP_abundance_matrix_rounded_5p_v2v4[, -86]
#469 MSP

t(MSP_abundance_matrix_rounded_5p_v2v4) -> MSP_abundance_matrix_rounded_5p_v2v4
MSP_abundance_matrix_rounded_5p_v2v4 = as.data.frame (MSP_abundance_matrix_rounded_5p_v2v4)


sample_metadata_metaG_v2v4 = as.data.frame(sample_metadata_metaG_v2v4)
sample_metadata_metaG_v2v4$Groupe_dose = as.factor(sample_metadata_metaG_v2v4$Groupe_dose)
sample_metadata_metaG_v2v4$Groupe_dose = relevel(sample_metadata_metaG_v2v4$Groupe_dose, ref = "CP.3")

Tolerance::sample_metadata_metaG_v2v4 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head


dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_5p_v2v4[Tolerance::sample_metadata_metaG_v2v4$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_v2v4 %>%  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject, fitType='local')


results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(padj)

# L rhamnosus, L casei, clostridium leptum


```


## group effect and visit

```{r}
### sans appariement des sujets

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_5p_v2v4[Tolerance::sample_metadata_metaG_v2v4$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_v2v4 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Groupe + Visit:Groupe)

# converting counts to integer mode
# factor levels were dropped which had no samples

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Visit+Groupe, fitType='local')

results(dds_res1) %>% as.data.frame() %>%
      tibble::rownames_to_column("msp") %>% filter(padj < 0.05)

msp_lrhamnosus	3.367170	-2.223146	0.6191786	12.97493	3.156897e-04	
msp_0242	3.721304	3.256143	0.8632448	14.18191	1.659587e-04	
msp_0196	9.521848	-4.282881	0.9885371	17.67541	2.619923e-05	
msp_0052	7.217935	-3.847049	1.0083667	13.94001	1.887384e-04	
msp_0561	4.383926	-3.375000	0.8609520	15.23684	9.483518e-05


dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_5p_v2v4[Tolerance::sample_metadata_metaG_v2v4$samplenr,]) +1,
  colData = Tolerance::sample_metadata_metaG_v2v4 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"),
  design = ~ Visit + Groupe_dose + Visit:Groupe_dose)

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Visit+Groupe_dose,  fitType='local')

results(dds_res1) %>% as.data.frame() %>%
      tibble::rownames_to_column("msp") %>% filter(padj < 0.05)

msp_lrhamnosus	3.367170	-2.223146	0.6191786	12.97493	3.156897e-04
msp_0242
msp_0196
msp_0052
msp_0561


results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(padj)

msp_0196	9.521848	4.282881	0.9885373	17.67541	2.619923e-05	
msp_0242	3.721304	-3.256145	0.8632447	14.18191	1.659587e-04	
msp_0052	7.217935	3.847046	1.0083667	13.94001	1.887384e-04	
msp_0561	4.383926	3.374999	0.8609521	15.23684	9.483518e-05	
msp_lrhamnosus	3.367170	2.223147	0.6191786	12.97493	3.156897e-04	

dds_res1_msp_5p_no_appariement = results(dds_res1) %>% as.data.frame() %>%
      tibble::rownames_to_column("msp")
save(dds_res1_msp_5p_no_appariement, file="dds_res1_msp_5p_no_appariement.rda")
write.csv2(dds_res1_msp_5p_no_appariement, file="dds_res1_msp_5p_no_appariement.csv")


### avec appariement des sujets

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_abundance_matrix_rounded_5p_v2v4[Tolerance::sample_metadata_metaG_v2v4$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_v2v4 %>%  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject, fitType='local')


temp <- Tolerance::sample_metadata_metaG_v2v4 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.3") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)


# mod <- model.matrix(~ Groupe_dose + Groupe_dose:Visit, temp)
# mod <- mod[,colSums(mod)>0]
# dds2 <- estimateDispersions(dds2, modelMatrix = mod)


# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]
# 
# mod2 <- model.matrix(~ Groupe_dose, temp)
# mod2 = mod2[, colSums(mod2)>0]

dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)



save(dds2_res1, file="deseq2_dds2_res1_analysis.rda")

results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# pas de L rhmanosus, casei ou stepto

# msp_0127	45.889725	-1.005651	0.5406896	12.328098	0.002103718	0.5573137
# msp_0032	10.555294	-2.419586	0.5519849	12.084165	0.002376604	0.5573137
# msp_0201	4.884298	-1.618757	0.4808096	11.065200	0.003955690	0.5694348
# msp_0732	5.134211	-1.604758	0.4944199	10.058588	0.006543429	0.5694348
# msp_0502	2.130970	-1.249239	0.4337670	8.900080	0.011678098	0.6007884
# msp_0930	8.371766	-1.318475	0.4576442	8.865595	0.011881203	0.6007884
# msp_0027	42.790284	-1.931254	0.5727510	8.865204	0.011883530	0.6007884
# msp_1121	2.003859	-1.346837	0.4813426	8.537850	0.013996822	0.6007884
# msp_0177	14.739488	-2.193613	0.6134736	8.524440	0.014090987	0.6007884
# msp_0409	12.003577	-1.395795	0.4982942	7.836718	0.019873678	0.7174079


grep("msp_1025", rownames(dds2_res1))
#173

results(dds2_res1[173,], alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") 
# 
# msp
# <chr>
# baseMean
# <dbl>
# log2FoldChange
# <dbl>
# lfcSE
# <dbl>
# stat
# <dbl>
# pvalue
# <dbl>
# padj
# <dbl>
# msp_1025	2.140637	0.03954146	0.5509215	0.8099783	0.6669841	0.6669841



dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

#using supplied model matrix
#67 rows did not converge in beta, labelled in mcols(object)$betaConv. Use larger maxit argument with nbinomWaldTest

DESeq2::resultsNames(dds2_res2)


res_ATN3_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("msp")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05_MSP_5p.rda")

# msp_0127	45.88973	-3.17174	0.7488572	-4.23544	2.281045e-05	0.0106981


res_ATN3_CP3_v2v4_msp_all=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("msp")
save(res_ATN3_CP3_v2v4_msp_all, file="res_ATN3_CP3_v2v4_MSP_5p_all.rda")
write.csv2(res_ATN3_CP3_v2v4_msp_all, file="res_ATN3_CP3_v2v4_msp_all.csv")

grep("msp_1025", res_ATN3_CP3_v2v4$msp)
#173

results(dds2_res1[173,], alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") 


#### test en retirant le subject:n -> lrhamno et casei ressortent pas

```
