---
title: "pipeline benchmark from Tolerance study set"
output:
  html_notebook:
    highlight: tango
    author: Julien Tap
    mathjax: null
    theme: cerulean
    toc: yes
    toc_float: yes
    code_folding: hide
date: '`r Sys.Date()`'
---


```{r, message=FALSE, warning=FALSE}

devtools::load_all()
library(ggplot2)
library(magrittr)
library(dplyr)
library(reshape2)

```


get biom url from Tolerance data package

```{r}

usearch_lotus = system.file("biom", "OTU_lotus_usearchv7_32bit.biom", package="Tolerance")

usearch_qiime = system.file("biom", "otu_table_non_chimeric_usearch_qiime.biom", package="Tolerance")

vsearch_qiime = system.file("biom", "otu_table_non_chimeric_vsearch_qiime.biom", package="Tolerance")

dada_variant  = system.file("biom", "data_project.biom", package="Tolerance")

```


compute diversity stat

```{r}


diversity_raw_stat = function(biom_url){

b = biomformat::read_biom(biom_url)
o = biomformat::biom_data(b)
#o %>% as.matrix %>% t %>% vegan::rarefy(10000)

#o %>% as.matrix %>% t %>% vegan::rrarefy(10000) %>% vegan::diversity(., index="shannon") %>% rbind(shannon = ., o %>% as.matrix %>% t %>% vegan::rrarefy(10000) %>% vegan::estimateR()) %>% t


r = o %>% 
  as.matrix %>% 
  t %>% 
  vegan::rrarefy(10000) 

res = rbind(
simpson = vegan::diversity(r, index=c("simpson")),
shannon = vegan::diversity(r, index=c("shannon")),
vegan::estimateR(r)
) %>% t

return(res)

}


diversity_pipeline = 

rbind(
  cbind(diversity_raw_stat(usearch_lotus), pipeline = "usearch_lotus"),
  cbind(diversity_raw_stat(usearch_qiime), pipeline = "usearch_qiime"),
  cbind(diversity_raw_stat(vsearch_qiime), pipeline = "vsearch_qiime"),
  cbind(diversity_raw_stat(dada_variant) , pipeline = "dada2")
)




```

extract metadata and merge with diversity stat

```{r, message=FALSE, warning=FALSE}


b = biomformat::read_biom(usearch_lotus)

m = biomformat::sample_metadata(b)



stat = m %>% select(Description) %>% merge(diversity_pipeline,., by="row.names", all.x = TRUE) %>% melt(id.vars=c("Row.names","Description","pipeline"))

stat$value %<>% as.numeric

stat %<>% cbind(., stringr::str_split(stat$Description, pattern="\\.", simplify = TRUE) )

colnames(stat) = c("Subject","Description","pipeline","index","value","Visit","Product","Dose")


stat






```


```{r}

# 
# stat %>% filter(index=="S.obs") %>% 
#   ggplot() + 
#   geom_violin(aes(x=Visit, y=value), draw_quantiles = 0.5 ) + facet_grid(pipeline~Product+Dose, scales = "free_y")
# 


stat %>% filter(index=="S.obs") %>% 
  group_by(Visit, Product, Dose, pipeline) %>% 
  summarize(mean=median(value), q25 = quantile(value,0.25), q75 = quantile(value,0.75)) %>%  
  ggplot() +  geom_line(aes(y=mean, x=Visit, group=pipeline),  col="red") + 
  geom_line(aes(y=q25, x=Visit, group=pipeline), linetype=2) + 
  geom_line(aes(y=q75, x=Visit, group=pipeline), linetype=2) + 
  facet_grid(pipeline~Product+Dose, scales = "free_y") + ylab("S.chao1")



stat %>% filter(index=="simpson") %>% 
  group_by(Visit, Product, Dose, pipeline) %>% 
  summarize(mean=median(value), q25 = quantile(value,0.25), q75 = quantile(value,0.75)) %>%  
  ggplot() +  geom_line(aes(y=mean, x=Visit, group=pipeline),  col="red") + 
  geom_line(aes(y=q25, x=Visit, group=pipeline), linetype=2) + 
  geom_line(aes(y=q75, x=Visit, group=pipeline), linetype=2) + 
  facet_grid(pipeline~Product+Dose, scales = "free_y") + ylab("S.chao1")


stat %>% filter(index=="shannon") %>% 
  group_by(Visit, Product, Dose, pipeline) %>% 
  summarize(mean=median(value), q25 = quantile(value,0.25), q75 = quantile(value,0.75)) %>%  
  ggplot() +  geom_line(aes(y=mean, x=Visit, group=pipeline),  col="red") + 
  geom_line(aes(y=q25, x=Visit, group=pipeline), linetype=2) + 
  geom_line(aes(y=q75, x=Visit, group=pipeline), linetype=2) + 
  facet_grid(pipeline~Product+Dose, scales = "free_y") + ylab("S.chao1")


stat %>% filter(index=="S.chao1") %>% 
  group_by(Visit, Product, Dose, pipeline) %>% 
  summarize(mean=median(value), q25 = quantile(value,0.25), q75 = quantile(value,0.75)) %>%  
  ggplot() +  geom_line(aes(y=mean, x=Visit, group=pipeline),  col="red") + 
  geom_line(aes(y=q25, x=Visit, group=pipeline), linetype=2) + 
  geom_line(aes(y=q75, x=Visit, group=pipeline), linetype=2) + 
  facet_grid(pipeline~Product+Dose, scales = "free_y") + ylab("S.chao1")




```











```{r}

stat %>%  dcast(Visit+Product+Dose+Description+index+Subject~pipeline, value.var = "value") %>% filter(index=="S.chao1") %>% ggplot() + geom_point(aes(x=vsearch_qiime, y=usearch_qiime, col=Dose)) + facet_wrap(~Visit+Product)


stat %>% dcast(Visit+Product+Dose+index+Subject~pipeline, value.var = "value") %>% 
  filter(index=="S.obs") %>% 
  group_by(Visit,Product,Dose,index) %>% 
  do(melt(cor(.[,-c(1:5)], method="spearman"))) %>% 
  ggplot() + geom_tile(aes(x=Var1, y=Var2, fill=value)) + 
  facet_grid(Visit~Product+Dose) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0)) +
  xlab("pipeline") + ylab("") + scale_fill_gradient("Alpha_div\nCor.")
  
  
  
  
```




```{r}



get_genus_from_biom = function(biom_file){
  
  
  b     = biomformat::read_biom(biom_file)
  otu   = biomformat::biom_data(b)
  tax   = biomformat::observation_metadata(b)
  genus = apply(otu, 2, tapply, paste(tax[,1],tax[,2] ,tax[,3],tax[,4],tax[,5],tax[,6], sep="; "), sum)

  return(genus)  
  
}

genus_dada = get_genus_from_biom(dada_variant)

genus_usearch_qiime = get_genus_from_biom(usearch_qiime)

genus_vsearch_qiime = get_genus_from_biom(vsearch_qiime)

genus_usearch_lotus = get_genus_from_biom(usearch_lotus)


row.names(genus_usearch_lotus) %>% grep("Bifidobacterium|Faecalibacterium|Bacteroides|Lactobacillus|Akkermansia",., value=TRUE)



plot(genus_usearch_lotus %>% apply(.,2,sum), genus_dada %>% apply(.,2,sum))





```











