---
title: "ZIBR analysis"
output: html_notebook
---


```{r}
library(ggplot2)
library(dplyr)
library(ZIBR) #devtools::install_github("chvlyl/ZIBR")

devtools::load_all(reset=FALSE)


```

```{r}

data(sample_metadata)  

load("genus.rda")

genus


```



```{r}
genus %>%
  reshape2::melt(id.vars="genus") %>%
  group_by(variable) %>%
  mutate(nbReads=sum(value)) %>%
  mutate(prop = value/nbReads) %>% 
  #ungroup() %>%
  group_by(genus) %>%
  summarize(prop_max=max(na.omit(prop)), zero=sum(na.omit(value)>0)/length(value)) -> genus_stat_summary

#genus_stat_summary %>%
#  filter(prop_max>0.01, zero > 0.1 & zero < 0.9) %>% View()

#genus_stat_summary %>%
#  filter(prop_max>0.01, zero < 0.9) %>% View()

genus %>%
  reshape2::melt(id.vars="genus") %>%
  group_by(variable) %>%
  mutate(nbReads=sum(value)) %>%
  mutate(Offset=log(nbReads)) %>%
  merge(., sample_metadata,  by.x="variable", by.y="samplenr") %>%
  filter(Groupe %in% c("ATN","CP")) %>%
  mutate(fx = ifelse(Groupe=="ATN",1,0)) %>%
  mutate(fx2 = ifelse(Groupe_dose=="ATN.3",1,0)) %>%
  ungroup() %>%  
  #group_by(variable,Subject, taxonomy1, taxonomy2,taxonomy3, 
  #         taxonomy4, taxonomy5, taxonomy6) %>%
  #mutate(baseline=ifelse(Visit=="V2",value,value[Visit=="V2"])) %>%
  #mutate(baseline=mean(tmp)) %>%
  #select(-tmp) %>%
  mutate(value=value/nbReads) %>%
  mutate(Time = case_when(
    Visit=="V2" ~ 0,
    Visit=="V3" ~ 1,
    Visit=="V4" ~ 2,
    Visit=="V5" ~ 4
  )) %>%
  mutate(Challenge = case_when(
    Visit=="V2" ~ 0,
    Visit=="V3" ~ 1,
    Visit=="V4" ~ 2,
    Visit=="V5" ~ 0
  ))  %>%
  mutate(fx3 = case_when(
    fx=="1" & fx2=="1" ~ 3,
    fx=="1" & fx2=="0" ~ 1,
    fx=="0" & fx2=="0" ~ 0
    
  )) -> genus_metadata

genus_metadata_baseline =
genus_metadata %>%
  filter(Visit=="V2") %>%
  select(Subject,genus,value) %>%
  dplyr::rename(baseline=value) %>%
  merge(genus_metadata, by=c("Subject","genus")) %>%
  filter(Time > 0) %>%
  group_by(Subject,genus) %>%
  mutate(n=n()) %>%
  filter(n==3) %>% ungroup()


```

```{r}

spe="D_0__Bacteria; D_1__Firmicutes; D_2__Bacilli; D_3__Lactobacillales; D_4__Lactobacillaceae; D_5__Lactobacillus"

#spe = "D_0__Bacteria; D_1__Proteobacteria; D_2__Gammaproteobacteria; D_3__Enterobacteriales; D_4__Enterobacteriaceae; D_5__Escherichia-Shigella"

#spe="D_0__Bacteria; D_1__Bacteroidetes; D_2__Bacteroidia; D_3__Bacteroidales; D_4__Prevotellaceae; D_5__uncultured"


spe_df =
  genus_metadata_baseline %>%  
  filter(genus==spe)

est1 <- zibr(logistic.cov = spe_df %>% select(baseline,Challenge,fx3), 
            beta.cov     =  spe_df %>% select(baseline,Challenge,fx3),
            Y            =  spe_df %>% pull(value),
            subject.ind  =  spe_df %>% pull(Subject),
            time.ind     =  spe_df %>% pull(Time),
            quad.n=30,verbose=TRUE)

est1




spe_df %>% 
  mutate(Ylogit=value %>% car::logit(adjust=0)) %>% 
  ggplot() + 
  geom_boxplot(aes(y=Ylogit,x=Time%>%as.character(),fill=fx3%>%as.character()))

spe_df %>% 
  group_by(fx3,Time) %>%
  summarise(p = value %>% (function(x)(table(x>0)["TRUE"]/length(x)))) %>%
  ggplot() + 
  geom_bar(aes(x=Time%>%as.character(),fill=fx3%>%as.character(),y=p), 
           position="dodge", stat="identity")


```




```{r}
## make a big loop

genus_stat_summary %>%
  filter(prop_max>0.001 & zero > 0.1) %>%
  mutate(genus_id=genus) %>% 
  pull(genus_id) -> genus_select

zibr_est_list=vector("list",length(genus_select))


for(i in seq_along(genus_select)) {

cat(i,"start \n")  
  
spe=genus_select[i]

spe_df =
  genus_metadata_baseline %>%  
  mutate(genus_id=genus) %>% 
  filter(genus_id==spe)

est1 <- zibr(logistic.cov = spe_df %>% select(baseline,Challenge,fx3), 
            beta.cov     =  spe_df %>% select(baseline,Challenge,fx3),
            Y            =  spe_df %>% pull(value),
            subject.ind  =  spe_df %>% pull(Subject),
            time.ind     =  spe_df %>% pull(Time),
            quad.n=30,verbose=TRUE)

zibr_est_list[[i]] <- est1

cat(i,"done \n")

}

zibr_est_list %>% sapply(unlist) -> zibr_est_df

save(zibr_est_df, file="zibr_est_df.rda")

# 
# 
# 
# rownames(zibr_est_df)[1:10]  =
# paste("logistic.est", 
#       c(rep("estimate",5), rep("Pvalue",5)),
#       rep(c("Intercept","Baseline","Challenge","fx3"),2), sep=".")
# 
# rownames(zibr_est_df)[12:21]  =
# paste("beta.est", 
#       c(rep("estimate",5), rep("Pvalue",5)),
#       rep(c("Intercept","Baseline","Challenge","fx3"),2), sep=".")
#
```




```{r}
load("zibr_est_df.rda")
colnames(zibr_est_df) = genus_select

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  write.csv2(file="result_ZIBR.csv")

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3, beta.est.table3) %>%
  mutate(joint.p.fx3 = joint.p.fx3 %>% p.adjust(method = "fdr"), joint.p.Challenge = joint.p.Challenge %>% p.adjust(method = "fdr")) %>%
  #filter(joint.p.fx3<0.05) %>%
  arrange(( joint.p.fx3)) %>% 
  tidyr::separate(genus, into=LETTERS[2:7], sep=";", remove=FALSE ) %>%
  mutate(G=ifelse(joint.p.fx3<0.05|joint.p.Challenge<0.05,G,NA)) %>%
  ggplot() + 
  geom_point(aes(x=-log10(joint.p.Challenge+10^-12), y=-log10(joint.p.fx3+10^-12), size=abs(beta.est.table3)), alpha=0.5) +
  ggrepel::geom_text_repel(aes(x=-log10(joint.p.Challenge+10^-12), y=-log10(joint.p.fx3+10^-12), label=G%>%gsub("D_5__","",.))) +
  ylab("Dose effect\n(-log10(Qvalue))") + xlab("Test product consumption effect\n(-log10(Qvalue))") + theme_classic() +
  geom_hline(yintercept = -log10(0.05), alpha=0.5, color="red") + geom_vline(xintercept = -log10(0.05), alpha=0.5, color="red") +
  scale_size_continuous("absolute Test product\neffect estimate") #+
  #xlim(0,16) + ylim(0,16)

ggsave("Figure_ZIBR_pvalue.pdf")

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  mutate(joint.p.fx3 = joint.p.fx3 %>% p.adjust(method = "fdr"), joint.p.Challenge = joint.p.Challenge %>% p.adjust(method = "fdr")) %>%
  filter(joint.p.fx3<0.05 & joint.p.Challenge <0.05) %>% pull(genus) -> genus_select
```


```{r fig.height=5, fig.width=12}


load("zibr_est_df.rda")



genus %>%
  tibble::column_to_rownames("genus") %>%
  mutate_all(SpiecEasi::clr) -> genus_clr

row.names(genus_clr)=genus$genus

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  mutate(joint.p.fx3 = joint.p.fx3 %>% p.adjust(method = "fdr"), joint.p.Challenge = joint.p.Challenge %>% p.adjust(method = "fdr")) %>%
  filter(joint.p.fx3<0.05 & joint.p.Challenge <0.05) %>% pull(genus) -> genus_select



genus_clr[genus_select,] %>%
  tibble::rownames_to_column("genus") %>%
  reshape2::melt(id.vars="genus") %>%
  merge(sample_metadata, by.x="variable", by.y="samplenr") %>%
  ggplot() + geom_boxplot(aes(x=Visit,y=value,fill=Groupe %>% gsub("ATN","Test",.) %>% gsub("CP","Control",.)))  + 
  facet_grid(Doses~genus %>% gsub(";","\n",.)) + ylab("rel. abundance (CLR)") + 
  scale_fill_brewer("",type="qual") + theme_classic()


```



```{r fig.height=10, fig.width=6}

#read.csv2("result_ZIBR.csv") %>% select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>% mutate(joint.p.fx3 = joint.p.fx3 %>% p.adjust(method = "fdr"), joint.p.Challenge = joint.p.Challenge %>% p.adjust(method = "fdr")) %>% filter(joint.p.fx3<0.05 & joint.p.Challenge <0.05) %>% pull(genus) -> genus_select


genus %>%
  tibble::column_to_rownames("genus") %>%
  mutate_all(SpiecEasi::clr) -> genus_clr

row.names(genus_clr)=genus$genus

library(ade4)
library(purrr)

genus_clr_pca = dudi.pca(as.data.frame(genus_clr[genus_select,]%>%t), scannf = F, nf=3)

#genus_clr_pca = dudi.pca(as.data.frame(genus_clr%>%t), scannf = F, nf=3)

genus_clr_pca$eig/sum(genus_clr_pca$eig)

sample_metadata %>%
  merge(genus_clr_pca$li, by.x="samplenr", by.y="row.names") %>%
  filter(Visit %in% c("V2","V3","V4","V5")) %>%
  ggplot() + geom_point(aes(x=Axis1,y=Axis2,col=Groupe)) + 
  facet_grid(Visit~Doses)

PC2_boxplot_plot =
sample_metadata %>%
  merge(genus_clr_pca$li, by.x="samplenr", by.y="row.names") %>%
  filter(Visit %in% c("V2","V3","V4","V5")) %>%
  mutate(Visit = Visit %>% forcats::fct_recode(D0="V2",D14="V3",D28="V4",D56="V5")  ) %>%
  mutate(Groupe = Groupe %>% forcats::fct_recode(Control="CP",Test="ATN")  ) %>%
  ggplot() + 
  geom_boxplot(aes(x=Groupe,y=Axis2)) + 
  geom_jitter(aes(x=Groupe,y=Axis2), width = 0.1) + 
  facet_grid(Visit~Doses) + ylab(paste("PC2",round((genus_clr_pca$eig/sum(genus_clr_pca$eig))[2]*100,2),"%")) +
  theme_classic() + xlab("Group")

genus_pca_plot = 
genus_clr_pca$co %>%
  tibble::rownames_to_column("genus") %>%
  tidyr::separate(genus, into=LETTERS[2:7], sep=";", remove=FALSE ) %>%
  ggplot() + geom_segment(aes(x=0,y=0,xend=Comp1,yend=Comp2), arrow = arrow(length = unit(0.1,"cm")) ) +
  ggrepel::geom_text_repel(aes(x=Comp1,y=Comp2, label=paste0(E%>%gsub("D_3__","",.),F%>%gsub("D_4__","",.),"\n",G%>%gsub("D_5__","",.)))) +
  theme_classic() +
  ylab(paste("PC2",round((genus_clr_pca$eig/sum(genus_clr_pca$eig))[2]*100,2),"%")) +
  xlab(paste("PC1",round((genus_clr_pca$eig/sum(genus_clr_pca$eig))[1]*100,2),"%"))


cowplot::plot_grid(genus_pca_plot,PC2_boxplot_plot,ncol=1, labels="AUTO", rel_heights = c(1,1.2))

ggsave("figure_genus_pca_clr.pdf")

sample_metadata %>%
  merge(genus_clr_pca$li, by.x="samplenr", by.y="row.names") %>%
  filter(Visit %in% c("V3","V4")) %>%
  group_by(Visit,Doses) %>%
  tidyr::nest() %>%
  mutate(model = map(data, ~wilcox.test(Axis2 ~ Groupe, data = .))) %>%
  mutate(tidy = map(model, broom::tidy)) %>%
  tidyr::unnest(tidy, .drop = T) %>%
  arrange(p.value) %>%
  mutate(p.value=p.adjust(p.value,"fdr"))
  
sample_metadata %>%
  merge(genus_clr_pca$li, by.x="samplenr", by.y="row.names") %>%
  filter(Visit %in% c("V2","V3","V4","V5")) %>%
  group_by(Visit,Doses) %>%
  tidyr::nest() %>%
  mutate(model = map(data, ~wilcox.test(Axis1 ~ Groupe, data = .))) %>%
  mutate(tidy = map(model, broom::tidy)) %>%
  tidyr::unnest(tidy, .drop = T) %>%
  arrange(p.value) %>%
  mutate(p.value=p.adjust(p.value,"fdr"))

sample_metadata %>%
  merge(genus_clr_pca$li, by.x="samplenr", by.y="row.names") %>%
  filter(Visit %in% c("V2","V3","V4","V5")) %>%
  group_by(Doses) %>%
  tidyr::nest() %>%
  mutate(model = map(data, ~kruskal.test(Axis1 ~ paste(Groupe,Visit), data = .))) %>%
  mutate(tidy = map(model, broom::tidy)) %>%
  tidyr::unnest(tidy, .drop = T) %>%
  arrange(p.value) %>%
  mutate(p.value=p.adjust(p.value,"fdr"))

sample_metadata %>%
  merge(genus_clr_pca$li, by.x="samplenr", by.y="row.names") %>%
  filter(Visit %in% c("V2","V3","V4","V5")) %>%
  group_by(Doses) %>%
  tidyr::nest() %>%
  mutate(model = map(data, ~kruskal.test(Axis2 ~ paste(Groupe,Visit), data = .))) %>%
  mutate(tidy = map(model, broom::tidy)) %>%
  tidyr::unnest(tidy, .drop = T) %>%
  arrange(p.value) %>%
  mutate(p.value=p.adjust(p.value,"fdr"))


```




```{r}


spe="D_0__Bacteria; D_1__Firmicutes; D_2__Bacilli; D_3__Lactobacillales; D_4__Lactobacillaceae; D_5__Lactobacillus"

spe="D_0__Bacteria; D_1__Firmicutes; D_2__Clostridia; D_3__Clostridiales; D_4__Lachnospiraceae; D_5__Blautia"

spe="D_0__Bacteria; D_1__Firmicutes; D_2__Erysipelotrichia; D_3__Erysipelotrichales; D_4__Erysipelotrichaceae; D_5__Holdemania"

spe="D_0__Archaea; D_1__Euryarchaeota; D_2__Methanobacteria; D_3__Methanobacteriales; D_4__Methanobacteriaceae; D_5__Methanobrevibacter"

spe="D_0__Bacteria; D_1__Bacteroidetes; D_2__Bacteroidia; D_3__Bacteroidales; D_4__Porphyromonadaceae; D_5__Coprobacter"

spe_df =
  genus_metadata_baseline %>%  
  filter(genus==spe)


p1=spe_df %>% 
  mutate(Ylogit=value %>% car::logit(adjust=0)) %>% 
  ggplot() + 
  geom_boxplot(aes(y=Ylogit,x=(Time*2)%>%as.character(),fill=fx3%>%as.character()))

p2=spe_df %>% 
  group_by(fx3,Time) %>%
  summarise(p = value %>% (function(x)(table(x>0)["TRUE"]/length(x)))) %>%
  ggplot() + 
  geom_bar(aes(x=(Time*2)%>%as.character(),fill=fx3%>%as.character(),y=p), 
           position="dodge", stat="identity")


cowplot::plot_grid(
  p1 + 
    scale_fill_brewer("FMP dose") + 
    ylab("Rel. abundance\n(logit scaled)") + 
    xlab("Time\n(Weeks)"),
  p2+
    scale_fill_brewer("FMP dose") + 
    ylab("prevalence") +
    xlab("Time\n(Weeks)")
  ) 



```




```{r}

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  #select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  arrange(joint.p.fx3) %>%
  mutate(joint.p.fx3 = joint.p.fx3 %>% p.adjust(method = "fdr"), joint.p.Challenge = joint.p.Challenge %>% p.adjust(method = "fdr")) %>%
  #filter((beta.est.table4 < 0 & beta.est.table3 < 0) | (beta.est.table4 > 0 & beta.est.table3 > 0) |  (logistic.est.table4 < 0 & logistic.est.table3 < 0) | (logistic.est.table4 > 0 & logistic.est.table3 > 0)   ) %>%
  filter((beta.est.table4 < 0 & beta.est.table3 < -0.1 ) | (beta.est.table4 > 0 & beta.est.table3 > 0.1) ) %>%
  filter(joint.p.Challenge < 0.05 | joint.p.fx3 < 0.05)

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  #select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  arrange(joint.p.fx3) %>%
  mutate(joint.p.fx3 = joint.p.fx3 %>% p.adjust(method = "fdr"), 
         joint.p.Challenge = joint.p.Challenge %>% p.adjust(method = "fdr"),
         beta.est.table7 = beta.est.table7 %>% p.adjust(method = "fdr"),
         beta.est.table8 = beta.est.table8 %>% p.adjust(method = "fdr")) %>%
  #filter(beta.est.table7 < 0.05 | beta.est.table8 < 0.05) %>%
  filter((beta.est.table4 < -0.2 & beta.est.table3 < -0.2) | (beta.est.table4 > 0.2 & beta.est.table3 > 0.2) )


zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  arrange(joint.p.fx3) %>%
  mutate(joint.p.fx3 = joint.p.fx3 %>% p.adjust(method = "fdr"), joint.p.Challenge = joint.p.Challenge %>% p.adjust(method = "fdr")) %>%
  ggplot() + geom_point(aes(x=-log10(joint.p.fx3+10^-6),y=-log10(joint.p.Challenge+10^-6)))







zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  #select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  arrange(joint.p.fx3) %>%
  #mutate(beta.est.table7 = beta.est.table7 %>% p.adjust(method = "fdr"), beta.est.table8 = beta.est.table8 %>% p.adjust(method = "fdr")) %>%
  ggplot() + geom_point(aes(x=beta.est.table3,y=-log10(beta.est.table7)))


zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  #select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  arrange(joint.p.fx3) %>%
  #mutate(beta.est.table7 = beta.est.table7 %>% p.adjust(method = "fdr"), beta.est.table8 = beta.est.table8 %>% p.adjust(method = "fdr")) %>%
  ggplot() + geom_point(aes(x=beta.est.table4,y=-log10(beta.est.table8)))


zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  #select(genus,joint.p.baseline,joint.p.Challenge, joint.p.fx3) %>%
  arrange(joint.p.fx3) %>%
  mutate(beta.est.table7 = beta.est.table7 %>% p.adjust(method = "fdr"), beta.est.table8 = beta.est.table8 %>% p.adjust(method = "fdr")) %>%
  ggplot() + 
  geom_point(aes(x=beta.est.table4,y=beta.est.table3, col = (beta.est.table7 < 0.05 | beta.est.table8 < 0.05)  )) +
  ylab("Challenge effect (beta est.)") + 
  xlab("Dose effect (beta est.)") + 
  scale_color_discrete("fdr < 0.05")



```




```{r fig.height=5, fig.width=10}



spe="D_0__Bacteria; D_1__Firmicutes; D_2__Bacilli; D_3__Lactobacillales; D_4__Streptococcaceae; D_5__Streptococcus"


spe_df =
  genus_metadata_baseline %>%  
  filter(genus==spe)


p1=spe_df %>% 
  mutate(Ylogit=value %>% car::logit(adjust=0)) %>% 
  ggplot() + 
  geom_boxplot(aes(y=Ylogit,x=Time%>%as.character(),fill=fx3%>%as.character()))

p2=spe_df %>% 
  group_by(fx3,Time) %>%
  summarise(p = value %>% (function(x)(table(x>0)["TRUE"]/length(x)))) %>%
  ggplot() + 
  geom_bar(aes(x=Time%>%as.character(),fill=fx3%>%as.character(),y=p), 
           position="dodge", stat="identity")


cowplot::plot_grid(p1,p2)


```




```{r}

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>% 
  mutate(joint.p.Time.fdr=p.adjust(joint.p.Time, method = "fdr"),
         joint.p.fx.fdr=p.adjust(joint.p.fx, method = "fdr"),
         joint.p.fx2.fdr=p.adjust(joint.p.fx2, method = "fdr"),
         joint.p.baseline.fdr=p.adjust(joint.p.baseline, method = "fdr")) %>%
write.csv2(file="result_ZIBR_fdr.csv")

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  mutate(joint.p.Time.fdr=p.adjust(joint.p.Time, method = "fdr"),
         joint.p.fx.fdr=p.adjust(joint.p.fx, method = "fdr"),
         joint.p.fx2.fdr=p.adjust(joint.p.fx2, method = "fdr"),
         joint.p.baseline.fdr=p.adjust(joint.p.baseline, method = "fdr")) %>%
  filter(joint.p.fx.fdr <0.05 | joint.p.fx2.fdr <0.05) 

zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  mutate(joint.p.Time.fdr=p.adjust(joint.p.Time, method = "fdr"),
         joint.p.fx.fdr=p.adjust(joint.p.fx, method = "fdr"),
         joint.p.fx2.fdr=p.adjust(joint.p.fx2, method = "fdr"),
         joint.p.baseline.fdr=p.adjust(joint.p.baseline, method = "fdr")) %>%
  filter(joint.p.fx.fdr <0.05) 




zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(joint.p.Time < 0.05|joint.p.fx <0.05 | joint.p.fx2 <0.05) %>%
  #arrange(desc(abs(beta.est.estimate.fx))) %>%
  top_n(5,abs(beta.est.estimate.fx)) %>%
  select(genus, beta.est.estimate.fx)


zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(joint.p.Time < 0.05 & joint.p.fx2 <0.05 ) %>%
  select(genus)
  
zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(joint.p.Time <0.05 & (joint.p.fx <0.05|joint.p.fx2 <0.05) ) %>%
  select(genus,joint.p.Time, joint.p.fx, joint.p.fx2)



zibr_est_df %>%
  t %>%
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  ggplot() + geom_point(aes(y=beta.est.estimate.fx,x=logistic.est.estimate.fx))

```



```{r}

spe="D_0__BacteriaD_1__FirmicutesD_2__BacilliD_3__LactobacillalesD_4__LactobacillaceaeD_5__Lactobacillus"

  
spe_df =
  genus_metadata_baseline %>%  
  mutate(genus_id=paste0(taxonomy1, taxonomy2,taxonomy3, 
                         taxonomy4, taxonomy5, taxonomy6)) %>% 
  filter(genus_id==spe)


spe_df %>% 
  mutate(Ylogit=value %>% car::logit(adjust=0)) %>% 
  ggplot() + 
  geom_boxplot(aes(y=Ylogit,x=Time%>%as.character(),fill=Groupe_dose%>% as.character()))

spe_df %>% 
  group_by(Groupe_dose,Time) %>%
  summarise(p = value %>% (function(x)(table(x>0)["TRUE"]/length(x)))) %>%
  ggplot() + 
  geom_bar(aes(x=Time%>%as.character(),fill=Groupe_dose%>% as.character(),y=p), 
           position="dodge", stat="identity")

```

