---
title: "Differential analysis -16S- selection of subjects with all visits"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
library(cowplot)
devtools::load_all(reset=FALSE)
```


```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}
```




### 1. Global differential analysis

# selection of subjects with all visits

```{r}

sample_metadata_allvisits = read.csv2("~/tolerance/data/sample_metadata_subjectswithallvisits.csv")
sample_metadata_allvisits = sample_metadata_allvisits[sample_metadata_allvisits$all_visits=="1",]
#324 samples (instead of 349) 81 subjects

sample_metadata_allvisits$samplenr = as.character(sample_metadata_allvisits$samplenr)
sample_metadata_allvisits$Subject = as.factor(sample_metadata_allvisits$Subject)

sample_metadata_allvisits$Groupe_dose = as.factor(sample_metadata_allvisits$Groupe_dose)
sample_metadata_allvisits$Groupe_dose = relevel(sample_metadata_allvisits$Groupe_dose, ref = "CP.1") 
save(sample_metadata_allvisits, file="~/tolerance/data/sample_metadata_allvisits.rda")
load("~/tolerance/data/sample_metadata_allvisits.rda")

load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allvisits = genus_tmp[match(sample_metadata_allvisits$samplenr, colnames(genus_tmp))]
genus_dose_allvisits$genus= rownames(genus_dose_allvisits)
genus= genus_dose_allvisits
save(genus, file="~/tolerance/data/genus_dose_allvisits.rda")
load("~/tolerance/data/genus_dose_allvisits.rda")

```

```{r}

genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allvisits %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
  
```

## global time effect

```{r}

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allvisits$samplenr,]), 
  colData = Tolerance::sample_metadata_allvisits %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

# dds1_res1 <- DESeq(dds1, test="LRT", sfType="poscounts", reduced= ~Subject_ID)
# results(dds1_res1, alpha=0.05)



res_dds_res1 =
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)
save(dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits.rda")
load("deseq2_16S_dds_res1_time_effect_subjecswithallvisits.rda")
write.csv2(res_dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits.csv")

# Lactobacillus 195.946678       1.029026 1.2710622  69.61654 5.156629e-15 1.143053e-13

```

## product and time effect (ATN1,ATN3,CP1,CP3,v2,v3,v4,v5)

```{r}

temp <- Tolerance::sample_metadata_allvisits #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.1") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")



# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
mod <- mod[colnames(dds2),]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

save(dds2, file="~/tolerance/notebook/dds2_16S_subjecs_with_all_visits_082019.rda")
load("~/tolerance/notebook/dds2_16S_subjecs_with_all_visits_082019.rda")

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]
mod2 <- mod2[colnames(dds2),]


##### test RLT ######


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

res_dds2_res1=
results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

save(dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits.rda")
write.csv2(res_dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits.csv")
load("deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits.rda")

# Lactobacillus 230.873223      -1.911436 0.6250550  24.91558 1.522802e-02 8.438859e-02


res=
results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)



##### contrasts to do graph with LRT test #####

# ATN1 vs CP1 by Visit


res_ATN1_CP1_v2v3=
results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV3","Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v3, file="res_ATN1_CP1_v2v3_p0.05_082019_LRT_padj0.05.rda")
write.csv2(res_ATN1_CP1_v2v3, file="res_ATN1_CP1_v2v3_p0.05_082019_LRT_padj0.05.csv")

res_ATN1_CP1_v2v4=
results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v4, file="res_ATN1_CP1_v2v4_p0.05_082019_LRT_padj0.05.rda")
write.csv2(res_ATN1_CP1_v2v4, file="res_ATN1_CP1_v2v4_p0.05_082019_LRT_padj0.05.csv")

res_ATN1_CP1_v2v5=
results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV5","Groupe_doseCP.1.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v5, file="res_ATN1_CP1_v2v5_p0.05_082019_LRT_padj0.05.rda")
write.csv2(res_ATN1_CP1_v2v5, file="res_ATN1_CP1_v2v5_p0.05_082019_LRT_padj0.05.csv")



# ATN3 vs CP3 by Visit


res_ATN3_CP3_v2v3=
results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05_082019_LRT_padj0.05.rda")
write.csv2(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05_082019_LRT_padj0.05.csv")

res_ATN3_CP3_v2v4=
results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05_082019_LRT_padj0.05.rda")
write.csv2(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05_082019_LRT_padj0.05.csv")

res_ATN3_CP3_v2v5=
results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v5, file="res_ATN3_CP3_v2v5_p0.05_082019_LRT_padj0.05.rda")
write.csv2(res_ATN3_CP3_v2v5, file="res_ATN3_CP3_v2v5_p0.05_082019_LRT_padj0.05.csv")


# plot ATN1/CP1 v3,v4,v5 normalized by v2 (with a padjusted<0.05) - test LRT


tiff(file="DESeq2_ATN1_CP1_allvisits_082019_LRT_padj0.05.tiff", w=1500, h=500) 
rbind(
    data.frame(res_ATN1_CP1_v2v3,visit="D14"),
    data.frame(res_ATN1_CP1_v2v4,visit="D28"), 
    data.frame(res_ATN1_CP1_v2v5,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()


# plot ATN3/CP3 v3,v4,v5 normalized by v2 (with a padjusted<0.05) - test LRT


tiff(file="DESeq2_ATN3_CP3_allvisits_082019_LRT_padj0.05.tiff", w=1500, h=500) 
rbind(
    data.frame(res_ATN3_CP3_v2v3,visit="D14"),
    data.frame(res_ATN3_CP3_v2v4,visit="D28"), 
    data.frame(res_ATN3_CP3_v2v5,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()




##### test Wald ######

dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

save(dds2_res2, file="~/tolerance/notebook/dds2_res2_16S_subjecs_with_all_visits_082019.rda")


# results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
#   data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# # 0 genres
# 
# results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
#   data.frame() %>% tibble::rownames_to_column("genus") 
# # Lactobacillus 2.308732e+02     1.51950016  0.8613333  1.764125557 0.07771084 0.6943388
# 
# res_dds2_res2_allvisits_ATN3CP3_V4V2 = 
# results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
#   data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
# save(res_dds2_res2_allvisits_ATN3CP3_V4V2, file="~/tolerance/notebook/res_dds2_res2_allvisits_ATN3CP3_V4V2_p0.1.rda")
# write.csv2(res_dds2_res2_allvisits_ATN3CP3_V4V2, file="~/tolerance/notebook/res_dds2_res2_allvisits_ATN3CP3_V4V2_p0.1.csv")
# 
# res_dds2_res2_allvisits_ATN3CP3_V3V2 = 
# results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
#   data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
# save(res_dds2_res2_allvisits_ATN3CP3_V3V2, file="~/tolerance/notebook/res_dds2_res2_allvisits_ATN3CP3_V3V2_p0.1.rda")
# write.csv2(res_dds2_res2_allvisits_ATN3CP3_V3V2, file="~/tolerance/notebook/res_dds2_res2_allvisits_ATN3CP3_V3V2_p0.1.csv")




##### contrasts to do graph with wald test #####

# ATN1 vs CP1 by Visit

res_ATN1_CP1_v2=
  results(dds2_res2, contrast = list("Groupe_doseATN.1"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2, file="res_ATN1_CP1_v2_p0.05_082019.rda")
write.csv2(res_ATN1_CP1_v2, file="res_ATN1_CP1_v2_p0.05_082019.csv")


res_ATN1_CP1_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV3","Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v3, file="res_ATN1_CP1_v2v3_p0.05_082019.rda")
write.csv2(res_ATN1_CP1_v2v3, file="res_ATN1_CP1_v2v3_p0.05_082019.csv")

res_ATN1_CP1_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v4, file="res_ATN1_CP1_v2v4_p0.05_082019.rda")
write.csv2(res_ATN1_CP1_v2v4, file="res_ATN1_CP1_v2v4_p0.05_082019.csv")

res_ATN1_CP1_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV5","Groupe_doseCP.1.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN1_CP1_v2v5, file="res_ATN1_CP1_v2v5_p0.05_082019.rda")
write.csv2(res_ATN1_CP1_v2v5, file="res_ATN1_CP1_v2v5_p0.05_082019.csv")



res_ATN1_CP1_v2v3_pval0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV3","Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
save(res_ATN1_CP1_v2v3_pval0.1, file="res_ATN1_CP1_v2v3_pval0.1_082019.rda")
write.csv2(res_ATN1_CP1_v2v3_pval0.1, file="res_ATN1_CP1_v2v3_pval0.1_082019.csv")

res_ATN1_CP1_v2v4_pval0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
save(res_ATN1_CP1_v2v4_pval0.1, file="res_ATN1_CP1_v2v4_pval0.1_082019.rda")
write.csv2(res_ATN1_CP1_v2v4_pval0.1, file="res_ATN1_CP1_v2v4_pval0.1_082019.csv")

res_ATN1_CP1_v2v5_pval0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV5","Groupe_doseCP.1.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
save(res_ATN1_CP1_v2v5_pval0.1, file="res_ATN1_CP1_v2v5_pval0.1_082019.rda")
write.csv2(res_ATN1_CP1_v2v5_pval0.1, file="res_ATN1_CP1_v2v5_pval0.1_082019.csv")




# ATN3 vs CP3 by Visit

res_ATN3_CP3_v2=
results(dds2_res2, contrast = list("Groupe_doseATN.3","Groupe_doseCP.3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2, file="res_ATN3_CP3_v2_p0.05_082019.rda")
write.csv2(res_ATN3_CP3_v2, file="res_ATN3_CP3_v2_p0.05_082019.csv")


res_ATN3_CP3_v2v3=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05_082019.rda")
write.csv2(res_ATN3_CP3_v2v3, file="res_ATN3_CP3_v2v3_p0.05_082019.csv")

res_ATN3_CP3_v2v3_p0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.1)
save(res_ATN3_CP3_v2v3_p0.1, file="res_ATN3_CP3_v2v3_p0.1_082019.rda")
write.csv2(res_ATN3_CP3_v2v3_p0.1, file="res_ATN3_CP3_v2v3_p0.1_082019.csv")


res_ATN3_CP3_v2v4=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05_082019.rda")
write.csv2(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05_082019.csv")

res_ATN3_CP3_v2v4_p0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.1)
save(res_ATN3_CP3_v2v4_p0.1, file="res_ATN3_CP3_v2v4_p0.1_082019.rda")
write.csv2(res_ATN3_CP3_v2v4_p0.1, file="res_ATN3_CP3_v2v4_p0.1_082019.csv")


# res_ATN3_CP3_v2v4_all=
# results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
#   data.frame() %>% tibble::rownames_to_column("genus") 
# save(res_ATN3_CP3_v2v4_all, file="res_ATN3_CP3_v2v4_all.rda")
# write.csv2(res_ATN3_CP3_v2v4_all, file="res_ATN3_CP3_v2v4_all.csv")

res_ATN3_CP3_v2v5=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v5, file="res_ATN3_CP3_v2v5_p0.05_082019.rda")
write.csv2(res_ATN3_CP3_v2v5, file="res_ATN3_CP3_v2v5_p0.05_082019.csv")

res_ATN3_CP3_v2v5_p0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.1)
save(res_ATN3_CP3_v2v5_p0.1, file="res_ATN3_CP3_v2v5_p0.1_082019.rda")
write.csv2(res_ATN3_CP3_v2v5_p0.1, file="res_ATN3_CP3_v2v5_p0.1_082019.csv")

results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<1)



res_ATN3_CP3_v2v3_pval0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV3","Groupe_doseCP.3.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
save(res_ATN3_CP3_v2v3_pval0.1, file="res_ATN3_CP3_v2v3_pval0.1_082019.rda")
write.csv2(res_ATN3_CP3_v2v3_pval0.1, file="res_ATN3_CP3_v2v3_pval0.1_082019.csv")


res_ATN3_CP3_v2v4_pval0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
save(res_ATN3_CP3_v2v4_pval0.1, file="res_ATN3_CP3_v2v4_pval0.1_082019.rda")
write.csv2(res_ATN3_CP3_v2v4_pval0.1, file="res_ATN3_CP3_v2v4_pval0.1_082019.csv")


res_ATN3_CP3_v2v5_pval0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV5","Groupe_doseCP.3.VisitV5"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
save(res_ATN3_CP3_v2v5_pval0.1, file="res_ATN3_CP3_v2v5_pval0.1_082019.rda")
write.csv2(res_ATN3_CP3_v2v5_pval0.1, file="res_ATN3_CP3_v2v5_pval0.1_082019.csv")







# plot ATN1/CP1 v3,v4,v5 normalized by v2 (with a padjusted<0.05) - test WALD

tiff(file="DESeq2_ATN1_CP1_allvisits_082019.tiff", w=1500, h=500) 
rbind(
    data.frame(res_ATN1_CP1_v2v3,visit="D14"),
    data.frame(res_ATN1_CP1_v2v4,visit="D28"), 
    data.frame(res_ATN1_CP1_v2v5,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()





# plot ATN1/CP1 v3,v4,v5 normalized by v2 (with a pvalue<0.1)

tiff(file="DESeq2_ATN1_CP1_allvisits_pvalue0.1_082019.tiff", w=1500, h=500) 

p1=
  
rbind(
    data.frame(res_ATN1_CP1_v2v3_pval0.1,visit="D14"),
    data.frame(res_ATN1_CP1_v2v4_pval0.1,visit="D28"), 
    data.frame(res_ATN1_CP1_v2v5_pval0.1,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()



# plot ATN3/CP3 v3,v4,v5 normalized by v2 (0 genus discriminant with a padjusted<0.05)

tiff(file="DESeq2_ATN3_CP3_allvisits_noD0.tiff", w=1500, h=500) 
rbind(
    data.frame(res_ATN3_CP3_v2v3,visit="D14"),
    data.frame(res_ATN3_CP3_v2v4,visit="D28"), 
    data.frame(res_ATN3_CP3_v2v5,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()


# plot ATN3/CP3 v3,v4,v5 normalized by v2 (with a padjusted<0.1)


tiff(file="DESeq2_ATN3_CP3_allvisits_082019_p0.1.tiff", w=1500, h=500) 
rbind(
    data.frame(res_ATN3_CP3_v2v3_p0.1,visit="D14"),
    data.frame(res_ATN3_CP3_v2v4_p0.1,visit="D28"), 
    data.frame(res_ATN3_CP3_v2v5_p0.1,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()


# plot ATN3/CP3 v3,v4,v5 normalized by v2 (with a pvalue<0.1)


tiff(file="DESeq2_ATN3_CP3_allvisits_pvalue0.1_082019.tiff", w=1500, h=500) 

p2=

rbind(
    data.frame(res_ATN3_CP3_v2v3_pval0.1,visit="D14"),
    data.frame(res_ATN3_CP3_v2v4_pval0.1,visit="D28"), 
    data.frame(res_ATN3_CP3_v2v5_pval0.1,visit="D56")
              ) %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + facet_wrap(~visit, scale="free_x", nrow=1)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()



tiff(file="~/tolerance/notebook/DESeq2_allATNCP_allvisits_pvalue0.1_082019.tiff", w=1000, h=1000)
plot_grid(p1,p2,nrow=2, ncol=1,labels=c("A","B"), label_size =22)
dev.off()


```

# selection des samples uniquement au temps V2 et V4 et de la dose 3

```{r}

sample_metadata_allvisits_v2v4 = sample_metadata_allvisits[sample_metadata_allvisits$Visit=="V2" | sample_metadata_allvisits$Visit=="V4",]
#162 samples (instead of 324 samples)

sample_metadata_allvisits_v2v4_dose3 = sample_metadata_allvisits_v2v4[sample_metadata_allvisits_v2v4$Doses=="3",]
# 80 samples

sample_metadata_allvisits_v2v4_dose3$samplenr = as.character(sample_metadata_allvisits_v2v4_dose3$samplenr)

sample_metadata_allvisits_v2v4_dose3$Subject = as.character(sample_metadata_allvisits_v2v4_dose3$Subject)

sample_metadata_allvisits_v2v4_dose3$Groupe_dose = as.factor(sample_metadata_allvisits_v2v4_dose3$Groupe_dose)

sample_metadata_allvisits_v2v4_dose3$Groupe_dose = relevel(sample_metadata_allvisits_v2v4_dose3$Groupe_dose, ref = "CP.3") 

save(sample_metadata_allvisits_v2v4_dose3, file="~/tolerance/data/sample_metadata_allvisits_v2v4_dose3.rda")
load("~/tolerance/data/sample_metadata_allvisits_v2v4_dose3.rda")


load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allvisits_v2v4_dose3 = genus_tmp[match(sample_metadata_allvisits_v2v4_dose3$samplenr, colnames(genus_tmp))]
genus_dose_allvisits_v2v4_dose3$genus= rownames(genus_dose_allvisits_v2v4_dose3)
genus= genus_dose_allvisits_v2v4_dose3
save(genus, file="~/tolerance/data/genus_dose_allvisits_v2v4_dose3.rda")
load("~/tolerance/data/genus_dose_allvisits_v2v4_dose3.rda")


genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allvisits_v2v4_dose3 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
  

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allvisits_v2v4_dose3$samplenr,]), 
  colData = Tolerance::sample_metadata_allvisits_v2v4_dose3 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)




dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

res_dds_res1 =
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# Lactobacillus 142.97499       3.233483 1.8325350 28.509959 9.321778e-08 1.938930e-06

save(dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v4_dose3.rda")
load("deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v4_dose3.rda")
write.csv2(res_dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v4_dose3.csv")








temp <- Tolerance::sample_metadata_allvisits_v2v4_dose3 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.3") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]



### Test LRT  ###


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

res_dds2_res1=
results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# Lactobacillus 153.754874       3.691458 0.6072433  28.781558 5.625538e-07 1.170112e-05
# Streptococcus 432.755697       1.377449 0.3764256  10.802871 4.510102e-03 2.759121e-02

save(dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose3.rda")
write.csv2(res_dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose3.csv")
load("deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose3.rda")

results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# Lactobacillus 153.754874      1.4847892 0.8464087  28.781558 5.625538e-07 1.170112e-05




##### contrasts to do graph with LRT test #####

# ATN3 vs CP3 by Visit

res_ATN3_CP3_v2v4=
results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05_082019_LRT_padj0.05_targeted.rda")
write.csv2(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05_082019_LRT_padj0.05_targeted.csv")



tiff(file="DESeq2_subjecswithallvisits_v2v4_dose3_ATN3_CP3_082019_LRT_padj0.05_targeted.tiff", w=1500, h=500) 

  res_ATN3_CP3_v2v4 %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + 
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()





### Test wald  ###


dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

save(dds2_res2, file="dds2_res2_subjecswithallvisits_v2v4_dose3.rda")

res_dds2_res2_subjecswithallvisits_v2v4_dose3_p0.05 = 
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# 1 D_0__Bacteria; D_1__Firmicutes; D_2__Bacilli; D_3__Lactobacillales; D_4__Streptococcaceae; D_5__Streptococcus
#   baseMean log2FoldChange     lfcSE     stat       pvalue       padj
# 1 432.7557       1.897235 0.5331388 3.558614 0.0003728165 0.03877291

save(res_dds2_res2_subjecswithallvisits_v2v4_dose3_p0.05,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose3_p0.05.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_v2v4_dose3_p0.05, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose3_p0.05.csv")


res_dds2_res2_subjecswithallvisits_v2v4_dose3 = 
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 
# Lactobacillus  153.754874    1.484789154 0.8464087  1.7542224003 0.0793924064 0.83492096

save(res_dds2_res2_subjecswithallvisits_v2v4_dose3,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose3.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_v2v4_dose3, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose3.csv")




##### contrasts to do graph #####

# ATN3 vs CP3 by Visit


res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_padj0.05=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_padj0.05, file="res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_padj0.05_082019.rda")
write.csv2(res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_padj0.05, file="res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_padj0.05_082019.csv")


res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.05=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.05)
save(res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.05, file="res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.05_082019.rda")
write.csv2(res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.05, file="res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.05_082019.csv")

res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.1=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(pvalue<0.1)
save(res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.1, file="res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.1_082019.rda")
write.csv2(res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.1, file="res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.1_082019.csv")


tiff(file="DESeq2_subjecswithallvisits_v2v4_dose3_ATN3_CP3_pvalue0.05_082019.tiff", w=1500, h=500) 

  res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.05 %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + 
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()




tiff(file="DESeq2_subjecswithallvisits_v2v4_dose3_ATN3_CP3_pvalue0.1_082019.tiff", w=1000, h=500) 

  res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_pvalue0.1 %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + 
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()




tiff(file="DESeq2_subjecswithallvisits_v2v4_dose3_ATN3_CP3_padjusted0.05_082019_wald_targeted.tiff", w=1500, h=500) 

  res_subjecswithallvisits_v2v4_dose3_ATN3_CP3_v2v4_padj0.05 %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + 
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()



```


# selection des samples uniquement la dose 3

```{r}


sample_metadata_allvisits_dose3 = sample_metadata_allvisits[sample_metadata_allvisits$Doses=="3",]
# 160 samples instead of 349 samples
sample_metadata_allvisits_dose3$samplenr = as.character(sample_metadata_allvisits_dose3$samplenr)

sample_metadata_allvisits_dose3$Subject = as.character(sample_metadata_allvisits_dose3$Subject)

sample_metadata_allvisits_dose3$Groupe_dose = as.factor(sample_metadata_allvisits_dose3$Groupe_dose)

sample_metadata_allvisits_dose3$Groupe_dose = relevel(sample_metadata_allvisits_dose3$Groupe_dose, ref = "CP.3") 

save(sample_metadata_allvisits_dose3, file="~/tolerance/data/sample_metadata_allvisits_dose3.rda")
load("~/tolerance/data/sample_metadata_allvisits_dose3.rda")


load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allvisits_dose3 = genus_tmp[match(sample_metadata_allvisits_dose3$samplenr, colnames(genus_tmp))]
genus_dose_allvisits_dose3$genus= rownames(genus_dose_allvisits_dose3)
genus= genus_dose_allvisits_dose3
save(genus, file="~/tolerance/data/genus_dose_allvisits_dose3.rda")
load("~/tolerance/data/genus_dose_allvisits_dose3.rda")


genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allvisits_dose3 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
  

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allvisits_dose3$samplenr,]), 
  colData = Tolerance::sample_metadata_allvisits_dose3 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

res_dds_res1 =
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# Lactobacillus 151.377787       3.179029 1.3824036  39.51919 1.347291e-08 2.672127e-07

save(dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_dose3.rda")
load("deseq2_16S_dds_res1_time_effect_subjecswithallvisits_dose3.rda")
write.csv2(res_dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_dose3.csv")



temp <- Tolerance::sample_metadata_allvisits_dose3 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.3") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

res_dds2_res1=
results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# Lactobacillus 170.203603      -2.676469 0.6710211  14.71290 2.261121e-02 1.169884e-01
# Streptococcus 538.554485      -1.220224 0.4151229  16.06912 1.338775e-02 1.053254e-01

save(dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_dose3.rda")
write.csv2(res_dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_dose3.csv")
load("deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_dose3.rda")

DESeq2::resultsNames(dds2_res1)

results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)

# Lactobacillus  170.203603   -0.546332929 0.9364520  1.471290e+01 2.261121e-02 1.169884e-01
# Streptococcus 538.554485    0.763542725 0.5867737  1.606912e+01 1.338775e-02 1.053254e-01


dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

res_dds2_res2_subjecswithallvisits_dose3_p0.05 = 
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# 0 

save(res_dds2_res2_subjecswithallvisits_dose3_p0.05,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose3_p0.05.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_dose3_p0.05, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose3_p0.05.csv")


res_dds2_res2_subjecswithallvisits_dose3 = 
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 
# Lactobacillus 170.203603   -0.546332929 0.9364520 -0.583407319 0.559619132 0.9977156

save(res_dds2_res2_subjecswithallvisits_dose3,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose3.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_dose3, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose3.csv")

```


# selection des samples uniquement au temps V2 et V4 et de la dose 1

```{r}

sample_metadata_allvisits_v2v4 = sample_metadata_allvisits[sample_metadata_allvisits$Visit=="V2" | sample_metadata_allvisits$Visit=="V4",]
# 162 samples (instead of 324 samples)

sample_metadata_allvisits_v2v4_dose1 = sample_metadata_allvisits_v2v4[sample_metadata_allvisits_v2v4$Doses=="1",]
# 82 samples

sample_metadata_allvisits_v2v4_dose1$samplenr = as.character(sample_metadata_allvisits_v2v4_dose1$samplenr)

sample_metadata_allvisits_v2v4_dose1$Subject = as.character(sample_metadata_allvisits_v2v4_dose1$Subject)

sample_metadata_allvisits_v2v4_dose1$Groupe_dose = as.factor(sample_metadata_allvisits_v2v4_dose1$Groupe_dose)

sample_metadata_allvisits_v2v4_dose1$Groupe_dose = relevel(sample_metadata_allvisits_v2v4_dose1$Groupe_dose, ref = "CP.1") 

save(sample_metadata_allvisits_v2v4_dose1, file="~/tolerance/data/sample_metadata_allvisits_v2v4_dose1.rda")
load("~/tolerance/data/sample_metadata_allvisits_v2v4_dose1.rda")


load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allvisits_v2v4_dose1 = genus_tmp[match(sample_metadata_allvisits_v2v4_dose1$samplenr, colnames(genus_tmp))]
genus_dose_allvisits_v2v4_dose1$genus= rownames(genus_dose_allvisits_v2v4_dose1)
genus= genus_dose_allvisits_v2v4_dose1
save(genus, file="~/tolerance/data/genus_dose_allvisits_v2v4_dose1.rda")
load("~/tolerance/data/genus_dose_allvisits_v2v4_dose1.rda")


genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allvisits_v2v4_dose1 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
  

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allvisits_v2v4_dose1$samplenr,]), 
  colData = Tolerance::sample_metadata_allvisits_v2v4_dose1 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

res_dds_res1 =
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# Lactobacillus 221.64484       1.060848 1.6581569 11.286286 7.808171e-04 1.154463e-02

save(dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v4_dose1.rda")
load("deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v4_dose1.rda")
write.csv2(res_dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v4_dose1.csv")


temp <- Tolerance::sample_metadata_allvisits_v2v4_dose1 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.1") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


#####  test LRT  #####

dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

res_dds2_res1=
results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# Lactobacillus 293.130276       2.509438 0.5195786  14.383945 7.526033e-04 1.128905e-02
# Streptococcus 512.675027       1.441385 0.4493609   6.915332 3.150320e-02 2.075267e-01

save(dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose1.rda")
write.csv2(res_dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose1.csv")
load("deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose1.rda")


res_dds2_res1_ATN1CP1_v2v4=
  results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

save(dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose1_ATN1CP1V2V4_padj0.05.rda")
write.csv2(res_dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v4_dose1_ATN1CP1V2V4_padj0.05.csv")


results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# Lactobacillus  293.130276     2.07835917 0.7214879  14.38394 7.526033e-04 1.128905e-02



##### contrasts to do graph with LRT test #####

# ATN1 vs CP1 by Visit

res_ATN1_CP1_v2v4=
results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4, file="res_ATN1_CP1_v2v4_p0.05_082019_LRT_padj0.05_targeted.rda")
write.csv2(res_ATN3_CP3_v2v4, file="res_ATN1_CP1_v2v4_p0.05_082019_LRT_padj0.05_targeted.csv")



tiff(file="DESeq2_subjecswithallvisits_v2v4_dose1_ATN1_CP1_082019_LRT_padj0.05_targeted.tiff", w=1500, h=500) 

  res_ATN1_CP1_v2v4 %>%
  
    tidyr::separate(col="genus", into=c("Domain","Phylum","Class","Order","Family","Genus"), sep="; ")%>%
filter(Domain != "Unassigned") %>%
# mutate(Genus = Genus %>% gsub("","Unassigned",.)) %>%  # je n'arrive pas à remplacer la cellule "vide" par unassigned"
mutate(Genus = Genus %>% gsub("D_5__","",.)) %>%
mutate(Family = Family %>% gsub("D_4__","",.)) %>%
mutate(Phylum = Phylum %>% gsub("D_1__","",.)) %>% 
filter(Genus != "Ambiguous_taxa") %>% 

    ggplot(aes(x=Genus,y=log2FoldChange, color=Phylum)) + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
  theme(axis.text.x = element_text(angle = -90, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + 
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()





####  test wald  ####



dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

res_dds2_res2_subjecswithallvisits_v2v4_dose1_p0.05 = 
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
#0

save(res_dds2_res2_subjecswithallvisits_v2v4_dose1_p0.05,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose1_p0.05.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_v2v4_dose1_p0.05, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose1_p0.05.csv")


res_dds2_res2_subjecswithallvisits_v2v4_dose1 = 
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 

# Lactobacillus 93.130276     2.07835917 0.7214879  2.880657104 0.003968471 0.1587388

save(res_dds2_res2_subjecswithallvisits_v2v4_dose1,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose1.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_v2v4_dose1, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2v4_dose1.csv")

load("res_dds2_res2_subjecswithallvisits_v2v4_dose1.rda")




```


# selection des samples uniquement avec la dose 1

```{r}


sample_metadata_allvisits_dose1 = sample_metadata_allvisits[sample_metadata_allvisits$Doses=="1",]
# 164 samples

sample_metadata_allvisits_dose1$samplenr = as.character(sample_metadata_allvisits_dose1$samplenr)

sample_metadata_allvisits_dose1$Subject = as.character(sample_metadata_allvisits_dose1$Subject)

sample_metadata_allvisits_dose1$Groupe_dose = as.factor(sample_metadata_allvisits_dose1$Groupe_dose)

sample_metadata_allvisits_dose1$Groupe_dose = relevel(sample_metadata_allvisits_dose1$Groupe_dose, ref = "CP.1") 

save(sample_metadata_allvisits_dose1, file="~/tolerance/data/sample_metadata_allvisits_dose1.rda")
load("~/tolerance/data/sample_metadata_allvisits_dose1.rda")


load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allvisits_dose1 = genus_tmp[match(sample_metadata_allvisits_dose1$samplenr, colnames(genus_tmp))]
genus_dose_allvisits_dose1$genus= rownames(genus_dose_allvisits_dose1)
genus= genus_dose_allvisits_dose1
save(genus, file="~/tolerance/data/genus_dose_allvisits_dose1.rda")
load("~/tolerance/data/genus_dose_allvisits_dose1.rda")


genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allvisits_dose1 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
  

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allvisits_dose1$samplenr,]), 
  colData = Tolerance::sample_metadata_allvisits_dose1 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

res_dds_res1 =
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# Lactobacillus 236.142202       1.905508 1.1459319  33.71899 2.271131e-07 4.693671e-06

save(dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_dose1.rda")
load("deseq2_16S_dds_res1_time_effect_subjecswithallvisits_dose1.rda")
write.csv2(res_dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_dose1.csv")


temp <- Tolerance::sample_metadata_allvisits_dose1 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.1") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

res_dds2_res1=
results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(pvalue<0.05, abs(log2FoldChange) > 1) %>%
  arrange(pvalue)

# no lactobacillus


res_dds2_res1=
  results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# lactobacillus 292.836080    0.377176531 0.5548926   7.957280640 2.412498e-01 6.364888e-01
save(dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_dose1_padj0.05.rda")
write.csv2(res_dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_dose1_padj0.05.csv")
load("deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_dose1_padj0.05.rda")

results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 
# Lactobacillus 292.836080     0.53178507 0.7708288   7.957280640 2.412498e-01 6.364888e-01

results(dds2_res1, contrast = list("Groupe_doseATN.1.VisitV3","Groupe_doseCP.1.VisitV3"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 
# Lactobacillus  292.836080    0.326027349 0.7700838   7.957280640 2.412498e-01 6.364888e-01

dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

res_dds2_res2_subjecswithallvisits_dose1_p0.05 = 
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# 1 D_0__Bacteria; D_1__Firmicutes; D_2__Clostridia; D_3__Clostridiales; D_4__Lachnospiraceae; D_5__Robinsoniella
#   baseMean log2FoldChange    lfcSE     stat       pvalue        padj
# 1  5.95768        35.1833 8.211178 4.284806 1.828991e-05 0.002267949

save(res_dds2_res2_subjecswithallvisits_dose1_p0.05,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose1_p0.05.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_dose1_p0.05, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose1_p0.05.csv")


res_dds2_res2_subjecswithallvisits_dose1_p0.05 = 
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)

save(res_dds2_res2_subjecswithallvisits_dose1_p0.05,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose1_p0.05.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_dose1, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose1_p0.05.csv")

res_dds2_res2_subjecswithallvisits_dose1 = 
results(dds2_res2, contrast = list("Groupe_doseATN.1.VisitV4","Groupe_doseCP.1.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 


save(res_dds2_res2_subjecswithallvisits_dose1,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose1.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_dose1, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_dose1.csv")

load("res_dds2_res2_subjecswithallvisits_dose1.rda")

# Lactobacillus 292.836080     0.53178507 0.7708288  0.689887424 4.902650e-01 0.998020166
```


# dose 3 visits V2, v3,v4


```{r}

sample_metadata_allvisits_v2v3v4 = sample_metadata_allvisits[sample_metadata_allvisits$Visit=="V2" | sample_metadata_allvisits$Visit=="V4" | sample_metadata_allvisits$Visit=="V3" ,]
# 243 samples (instead of 324 samples)

sample_metadata_allvisits_v2v3v4_dose3 = sample_metadata_allvisits_v2v3v4[sample_metadata_allvisits_v2v3v4$Doses=="3",]
# 120 samples

sample_metadata_allvisits_v2v3v4_dose3$samplenr = as.character(sample_metadata_allvisits_v2v3v4_dose3$samplenr)

sample_metadata_allvisits_v2v3v4_dose3$Subject = as.character(sample_metadata_allvisits_v2v3v4_dose3$Subject)

sample_metadata_allvisits_v2v3v4_dose3$Groupe_dose = as.factor(sample_metadata_allvisits_v2v3v4_dose3$Groupe_dose)

sample_metadata_allvisits_v2v3v4_dose3$Groupe_dose = relevel(sample_metadata_allvisits_v2v3v4_dose3$Groupe_dose, ref = "CP.3") 

save(sample_metadata_allvisits_v2v3v4_dose3, file="~/tolerance/data/sample_metadata_allvisits_v2v3v4_dose3.rda")
load("~/tolerance/data/sample_metadata_allvisits_v2v3v4_dose3.rda")


load("genus.rda")
rownames(genus)=genus$genus
genus_tmp = genus[,-1]
genus_dose_allvisits_v2v3v4_dose3 = genus_tmp[match(sample_metadata_allvisits_v2v3v4_dose3$samplenr, colnames(genus_tmp))]
genus_dose_allvisits_v2v3v4_dose3$genus= rownames(genus_dose_allvisits_v2v3v4_dose3)
genus= genus_dose_allvisits_v2v3v4_dose3
save(genus, file="~/tolerance/data/genus_dose_allvisits_v2v3v4_dose3.rda")
load("~/tolerance/data/genus_dose_allvisits_v2v3v4_dose3.rda")


genus %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("genus") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> genus_select


genus %>%
  filter(genus %in% genus_select) %>%
  tibble::column_to_rownames("genus") %>%
  t %>% as.data.frame-> genus_count


Tolerance::sample_metadata_allvisits_v2v3v4_dose3 %>%
  tibble::as_tibble() %>%
  as.data.frame() %>%
  tibble::column_to_rownames("samplenr") %>% head
  

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(genus_count[Tolerance::sample_metadata_allvisits_v2v3v4_dose3$samplenr,]), 
  colData = Tolerance::sample_metadata_allvisits_v2v3v4_dose3 %>% tibble::as_tibble() %>%
  as.data.frame() %>%
    tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)


dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)

res_dds_res1 =
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# Lactobacillus  183.185308       3.422080 1.4491661  33.304019 5.863058e-08 1.094437e-06

save(dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v3v4_dose3.rda")
load("deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v3v4_dose3.rda")
write.csv2(res_dds_res1, file="deseq2_16S_dds_res1_time_effect_subjecswithallvisits_v2v3v4_dose3.csv")


temp <- Tolerance::sample_metadata_allvisits_v2v3v4_dose3 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.3") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod)
# gene-wise dispersion estimates
# mean-dispersion relationship
# -- note: fitType='parametric', but the dispersion trend was not well captured by the
#    function: y = a/x + b, and a local regression fit was automatically substituted.
#    specify fitType='local' or 'mean' to avoid this message next time.
# final dispersion estimates

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)

res_dds2_res1=
results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("genus") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)
# NO LACTOBACILLUS
# 199.627572    0.505360629 0.6370199   2.751705290 6.001976e-01 9.468320e-01

save(dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v3v4_dose3.rda")
write.csv2(res_dds2_res1, file="deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v3v4_dose3.csv")
load("deseq2_16S_dds2_res1_LRT_time_product_subjecswithallvisits_v2v3v4_dose3.rda")



results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
# lACTOBACILLUS 199.627572    0.022851456 0.9002956   2.751705290 6.001976e-01 9.468320e-01

dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)

res_dds2_res2_subjecswithallvisits_v2V3v4_dose3_p0.05 = 
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus")  %>% filter(padj<0.05)
#0

save(res_dds2_res2_subjecswithallvisits_v2V3v4_dose3_p0.05,file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2V3v4_dose3_p0.05.rda")
write.csv2(res_dds2_res2_subjecswithallvisits_v2V3v4_dose3_p0.05, file="~/tolerance/notebook/res_dds2_res2_subjecswithallvisits_v2V3v4_dose3_p0.05.csv")


res_dds2_res2_subjecswithallvisits_v2v4_dose3 = 
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("genus") 

# Lactobacillus 199.627572    0.022851456 0.9002956  0.025382171 0.97975013 0.9980828
```
