---
title: "Differential analysis with MSP"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
devtools::load_all(reset=FALSE)

```



```{r}
# Function to get the new subject id
Get_New_Subject_ID = function(data_temp) {
  old = factor(data_temp$Subject)
  new_sub = paste0("S", 1:length(levels(old)))
  names(new_sub) = levels(old)
  return(data.frame(new_sub))
}

```


# samples metaG with allvisits v2 and v4 (n=76)
```{r}


Tolerance::sample_metadata_metaG_allvisits_v2v4 %>% head
str(sample_metadata_metaG_allvisits_v2v4$samplenr)

sample_metadata_metaG_allvisits_v2v4$samplenr = as.character(sample_metadata_metaG_allvisits_v2v4$samplenr)
str(sample_metadata_metaG_allvisits_v2v4$Subject)
sample_metadata_metaG_allvisits_v2v4$Subject = as.factor(sample_metadata_metaG_allvisits_v2v4$Subject) # je mets subject en factor sinon il me met un warning avec la fonction DESeqDataSetFromMatrix
str(sample_metadata_metaG_allvisits_v2v4$Sample)
sample_metadata_metaG_allvisits_v2v4$Sample = as.character(sample_metadata_metaG_allvisits_v2v4$Sample)

sample_metadata_metaG_allvisits_v2v4$Groupe_dose = as.factor(sample_metadata_metaG_allvisits_v2v4$Groupe_dose)
sample_metadata_metaG_allvisits_v2v4$Groupe_dose = relevel(sample_metadata_metaG_allvisits_v2v4$Groupe_dose, ref = "CP.3") 



load("~/tolerance/data/MSP_count_matrix_rounded_v2v4.rda")

MSP_count_matrix_rounded_v2v4$msp = rownames(MSP_count_matrix_rounded_v2v4)
MSP_count_matrix_rounded_v2v4 %>% head




```


## Filter abundant MSP
```{r}

MSP_count_matrix_rounded_v2v4 %>%
  mutate_if(is.numeric,function(x)(x/sum(x))) %>%
  tibble::column_to_rownames("msp") %>%
  BiotypeR::noise.removal(percent=0.1) %>% rownames() -> MSP_select
#673 MSP



MSP_count_matrix_rounded_v2v4 = MSP_count_matrix_rounded_v2v4[MSP_select,]
MSP_count_matrix_rounded_v2v4 = MSP_count_matrix_rounded_v2v4[, -77]

t(MSP_count_matrix_rounded_v2v4) -> MSP_count_matrix_rounded_v2v4
MSP_count_matrix_rounded_v2v4 = as.data.frame (MSP_count_matrix_rounded_v2v4)


Tolerance::sample_metadata_metaG_allvisits_v2v4 %>%
  tibble::column_to_rownames("samplenr") %>% head


```


## global time effect
```{r}

dds = DESeq2::DESeqDataSetFromMatrix(
  countData = t(MSP_count_matrix_rounded_v2v4[Tolerance::sample_metadata_metaG_allvisits_v2v4$samplenr,]) +1, 
  colData = Tolerance::sample_metadata_metaG_allvisits_v2v4 %>% tibble::column_to_rownames("samplenr"), 
  design = ~ Visit + Subject)

dds_res1 <- DESeq(dds, test="LRT",  reduced= ~Subject)
# estimating size factors
# estimating dispersions
# gene-wise dispersion estimates
# mean-dispersion relationship
# -- note: fitType='parametric', but the dispersion trend was not well captured by the
#    function: y = a/x + b, and a local regression fit was automatically substituted.
#    specify fitType='local' or 'mean' to avoid this message next time.
# final dispersion estimates
# fitting model and testing

save(dds_res1, file="deseq2_dds_res1_analysis_MSP_082019.rda")

res_dds_res1=
results(dds_res1, alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# signicant : L rhamnosus (+), Clostridium leptum (-), L casei

save(res_dds_res1, file="res_deseq2_dds_res1_analysis_MSP_082019.rda")
write.csv2(res_dds_res1, file="res_deseq2_dds_res1_analysis_MSP_082019.csv")

```


## Specific group effect and visit

```{r}

temp <- Tolerance::sample_metadata_metaG_allvisits_v2v4 #%>% tibble::column_to_rownames("samplenr")
temp <- temp[with(temp, order(Groupe_dose, Subject)), ]
new_sub <- data.frame(Reduce(rbind, 
                            by(as.data.frame(temp), 
                                temp$Groupe_dose, 
                                Get_New_Subject_ID, 
                                simplify = FALSE)))
names(new_sub) = "subject.n"
new_sub[, "Subject"] <- factor(rownames(new_sub))
temp = full_join(temp, 
                  new_sub, 
                  by = "Subject")
rownames(temp) <- temp$samplenr

temp # need here to force level factor

temp$Groupe_dose = as.factor(temp$Groupe_dose)
temp$Groupe_dose = relevel(temp$Groupe_dose, ref = "CP.3") 


# DESeq2 object and design matrices
dds2 <- dds
dds2 <- estimateSizeFactors(dds2, type="poscounts")

# Full design matrix
mod <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose + Groupe_dose:Visit, temp)
mod <- mod[,colSums(mod)>0]
dds2 <- estimateDispersions(dds2, modelMatrix = mod,fitType='local')

# Reduced design matrix
mod2 <- model.matrix(~ Groupe_dose:subject.n + Groupe_dose, temp)
mod2 = mod2[, colSums(mod2)>0]



####  test LRT  #####


dds2_res1 <- nbinomLRT(dds2, full = mod, reduced = mod2)
save(dds2_res1, file="deseq2_dds2_res1_analysis_MSP_LRT_082019.rda")

res_dds2_res1_LRT=
results(dds2_res1, alpha = 0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 1) %>%
  arrange(padj)

# signicant : L rhamnosus, Clostridium leptum, L casei  !!!!!!

save(res_dds2_res1_LRT, file="res_deseq2_dds2_res1_analysis_MSP_082019_LRT.rda")
write.csv2(res_dds2_res1_LRT, file="res_deseq2_dds2_res1_analysis_MSP_082019_LRT.csv")


res_ATN3_CP3_v2v4_LRT=
results(dds2_res1, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("msp")  %>% filter(padj<0.05)
save(res_ATN3_CP3_v2v4_LRT, file="res_ATN3_CP3_v2v4_MSP_082019_LRT_padj0.05.rda")
write.csv2(res_ATN3_CP3_v2v4_LRT, file="res_ATN3_CP3_v2v4_MSP_082019_LRT_padj0.05.csv")


res_ATN3_CP3_v2v4_LRT$MSP = res_ATN3_CP3_v2v4_LRT$msp


res_ATN3_CP3_v2v4_LRT %>%
  mutate(MSP = case_when(
    msp=="msp_0331" ~ "C. leptum",
    msp=="msp_1025" ~ "L. casei/paracasei",
    msp=="msp_lrhamnosus" ~ "L. rhamnosus"
  )) -> res_ATN3_CP3_v2v4_LRT



tiff(file="DESeq2_MSP_subjecswithallvisits_v2v4_dose3_ATN3_CP3_082019_LRT_padj0.05_angle45.tiff", w=800, h=500) 

  res_ATN3_CP3_v2v4_LRT %>%

    ggplot(aes(x=MSP,y=log2FoldChange, color=MSP), xlab="") + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
    xlab("")+
  theme(axis.text.x = element_text(angle = -45, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + 
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()





tiff(file="DESeq2_MSP_subjecswithallvisits_v2v4_dose3_ATN3_CP3_082019_LRT_padj0.05_angle0.tiff", w=800, h=500) 

  res_ATN3_CP3_v2v4_LRT %>%

    ggplot(aes(x=MSP,y=log2FoldChange, color=MSP), xlab="") + geom_point(size=3) +
    theme_set(theme_bw())+
  geom_hline(yintercept=0, color = "gray", linetype="dashed") +
    xlab("")+
  theme(axis.text.x = element_text(angle = 0, hjust=0))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=12, face="bold")) + 
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))

dev.off()






####  test wald  #####


dds2_res2 = nbinomWaldTest(dds2, modelMatrix = mod, betaPrior = FALSE)

DESeq2::resultsNames(dds2_res2)
# [1] "Intercept"                     "Groupe_doseATN.3"             
#  [3] "Groupe_doseCP.3.subject.nS10"  "Groupe_doseATN.3.subject.nS10"
#  [5] "Groupe_doseCP.3.subject.nS11"  "Groupe_doseATN.3.subject.nS11"
#  [7] "Groupe_doseCP.3.subject.nS12"  "Groupe_doseATN.3.subject.nS12"
#  [9] "Groupe_doseCP.3.subject.nS13"  "Groupe_doseATN.3.subject.nS13"
# [11] "Groupe_doseCP.3.subject.nS14"  "Groupe_doseATN.3.subject.nS14"
# [13] "Groupe_doseCP.3.subject.nS15"  "Groupe_doseATN.3.subject.nS15"
# [15] "Groupe_doseCP.3.subject.nS16"  "Groupe_doseATN.3.subject.nS16"
# [17] "Groupe_doseCP.3.subject.nS17"  "Groupe_doseATN.3.subject.nS17"
# [19] "Groupe_doseCP.3.subject.nS18"  "Groupe_doseATN.3.subject.nS18"
# [21] "Groupe_doseCP.3.subject.nS19"  "Groupe_doseATN.3.subject.nS19"
# [23] "Groupe_doseCP.3.subject.nS2"   "Groupe_doseATN.3.subject.nS2" 
# [25] "Groupe_doseCP.3.subject.nS20"  "Groupe_doseATN.3.subject.nS20"
# [27] "Groupe_doseCP.3.subject.nS21"  "Groupe_doseATN.3.subject.nS21"
# [29] "Groupe_doseCP.3.subject.nS22"  "Groupe_doseATN.3.subject.nS22"
# [31] "Groupe_doseCP.3.subject.nS23"  "Groupe_doseATN.3.subject.nS23"
# [33] "Groupe_doseCP.3.subject.nS24"  "Groupe_doseCP.3.subject.nS3"  
# [35] "Groupe_doseATN.3.subject.nS3"  "Groupe_doseCP.3.subject.nS4"  
# [37] "Groupe_doseATN.3.subject.nS4"  "Groupe_doseCP.3.subject.nS5"  
# [39] "Groupe_doseATN.3.subject.nS5"  "Groupe_doseCP.3.subject.nS6"  
# [41] "Groupe_doseATN.3.subject.nS6"  "Groupe_doseCP.3.subject.nS7"  
# [43] "Groupe_doseATN.3.subject.nS7"  "Groupe_doseCP.3.subject.nS8"  
# [45] "Groupe_doseATN.3.subject.nS8"  "Groupe_doseCP.3.subject.nS9"  
# [47] "Groupe_doseATN.3.subject.nS9"  "Groupe_doseCP.3.VisitV4"      
# [49] "Groupe_doseATN.3.VisitV4"      "Groupe_doseATN.3.VisitV5" 

save(dds2_res2, file="deseq2_dds2_res2_analysis_MSP_082019_wald.rda" )


res_ATN3_CP3_v2v4_MSP=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"), alpha = 0.05) %>% 
  data.frame() %>% tibble::rownames_to_column("msp")  %>% filter(padj<0.05)
# 0 MSP
save(res_ATN3_CP3_v2v4, file="res_ATN3_CP3_v2v4_p0.05.rda")

results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"),alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp") %>%
  filter(padj<0.05, abs(log2FoldChange) > 0.05) %>%
  arrange(padj)

# 0 MSP
res_dds2_res2_wald=
results(dds2_res2, contrast = list("Groupe_doseATN.3.VisitV4","Groupe_doseCP.3.VisitV4"),alpha=0.05) %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("msp")



save(res_dds2_res2_wald, file="res_deseq2_dds2_res2_analysis_MSP_082019_wald_allpvalue.rda")
write.csv2(res_dds2_res2_wald, file="res_deseq2_dds2_res2_analysis_MSP_082019_wald_allpvalue.csv")




```



