---
title: "MSP actineo abundance plot"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}

library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggsignif)
library(reshape2)
library(readr)
library(cowplot)

```

# load data
```{r}
# load taxo MSP
taxoMSP = read.csv2("~/actineo_paper/Rlocal_310719/taxo_1662msp.csv")

# load MSP relative abundance
load("~/actineo_paper/Rlocal_310719/MSP_relative_abundance_matrix_rounded.rda")

# load metadata
load("~/actineo_paper/sample_metadata_metaG_v2v4_010819.rda")

```



# select MSP actineo
```{r}

# msp_lrhamnosus
# msp_1200 Lactobacillus delbruckii
# msp_1025 Lactobacillus casei paracasei
# msp_0790 Streptococcus thermophilus

MSP_relative_abundance_matrix_rounded_t = t(MSP_relative_abundance_matrix_rounded)
MSP_relative_abundance_matrix_rounded_t = as.data.frame(MSP_relative_abundance_matrix_rounded_t)


sample_metadata_metaG_v2v4 = sample_metadata_metaG_v2v4[match(rownames(MSP_relative_abundance_matrix_rounded_t),sample_metadata_metaG_v2v4$samplenr),] 
all.equal(rownames(MSP_relative_abundance_matrix_rounded_t),sample_metadata_metaG_v2v4$samplenr)

MSP_relative_abundance_matrix_rounded_t$sample = rownames(MSP_relative_abundance_matrix_rounded_t)

sample_metadata_metaG_v2v4_MSP = merge(sample_metadata_metaG_v2v4, MSP_relative_abundance_matrix_rounded_t, by.x="samplenr", by.y="sample")

sample_metadata_metaG_v2v4_MSP %>% head

sample_metadata_metaG_v2v4_MSP$Groupe_dose = as.factor(sample_metadata_metaG_v2v4_MSP$Groupe_dose)

sample_metadata_metaG_v2v4_MSP$Visit = as.factor(sample_metadata_metaG_v2v4_MSP$Visit)

sample_metadata_metaG_v2v4_MSP$Groupe_dose = relevel(sample_metadata_metaG_v2v4_MSP$Groupe_dose, ref = "CP.3") 

summary(sample_metadata_metaG_v2v4_MSP)
save(sample_metadata_metaG_v2v4_MSP, file="~/actineo_paper/Rlocal_310719/sample_metadata_metaG_v2v4_MSP.rda")

load("~/actineo_paper/Rlocal_310719/sample_metadata_metaG_v2v4_MSP.rda")

```


# plot MSP actineo - individuals with samples at V2 and V4 (n=76, noATN v5)


```{r}


# plot L. rhamnosus

df.sample_metadata_metaG_v2v4_MSP = data.frame(sample_metadata_metaG_v2v4_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_lrhamnosus")])
m.sample_metadata_metaG_v2v4_MSP = melt(df.sample_metadata_metaG_v2v4_MSP)
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, variable = factor(variable, labels=c("Lactobacillus rhamnosus")))
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Visit = factor(Visit, labels=c("D0", "D28"), ordered=TRUE))


m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.sample_metadata_metaG_v2v4_MSP$value[m.sample_metadata_metaG_v2v4_MSP$value == 0 ]=1e-11

# m.sample_metadata_metaG_v2v4_MSP_Lacto_filterv2v4 = m.sample_metadata_metaG_MSP_Lacto %>% filter(Visit == "D0" | Visit == "D28")

my_comparisons <- list( c("FMP.3", "CP.3"))

p1=
 ggboxplot(m.sample_metadata_metaG_v2v4_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
            palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              ylab = "Log10 relative abundance L. rhamnosus",
              xlab= "",
              ggtheme = theme_pubr()) +
# scale_y_continuous(name = 'Gene richness', limits=c(0,1300000)) +
   scale_y_log10(name="Log10 relative abundance L. rhamnosus") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))



# msp_1025 Lactobacillus casei paracasei


df.sample_metadata_metaG_v2v4_MSP = data.frame(sample_metadata_metaG_v2v4_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_1025")])
m.sample_metadata_metaG_v2v4_MSP = melt(df.sample_metadata_metaG_v2v4_MSP)
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, variable = factor(variable, labels=c("Lactobacillus casei/paracasei")))
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Visit = factor(Visit, labels=c("D0", "D28"), ordered=TRUE))
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.sample_metadata_metaG_v2v4_MSP$value[m.sample_metadata_metaG_v2v4_MSP$value == 0 ]=1e-11


my_comparisons <- list( c("FMP.3", "CP.3"))

p2=
 ggboxplot(m.sample_metadata_metaG_v2v4_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
              palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              # ylab = "Log10 relative abundance L. casei/paracasei",
              xlab= "",
              ggtheme = theme_pubr()) +
   scale_y_log10(name="Log10 relative abundance L. casei/paracasei") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))



# msp_1200 Lactobacillus delbruckii

df.sample_metadata_metaG_v2v4_MSP = data.frame(sample_metadata_metaG_v2v4_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_1200")])
m.sample_metadata_metaG_v2v4_MSP = melt(df.sample_metadata_metaG_v2v4_MSP)
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, variable = factor(variable, labels=c("Lactobacillus delbruckii")))
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Visit = factor(Visit, labels=c("D0", "D28"), ordered=TRUE))
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.sample_metadata_metaG_v2v4_MSP$value[m.sample_metadata_metaG_v2v4_MSP$value == 0 ]=1e-11


my_comparisons <- list( c("FMP.3", "CP.3"))


p3=
 ggboxplot(m.sample_metadata_metaG_v2v4_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
            palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              # ylab = "Log10 Relative abundance L. amylovorus",
              xlab= "",
              ggtheme = theme_pubr()) +
   scale_y_log10(name="Log10 relative abundance L. delbruckii") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))


# msp_0970 Streptococcus thermophilus


df.sample_metadata_metaG_v2v4_MSP = data.frame(sample_metadata_metaG_v2v4_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_0790")])
m.sample_metadata_metaG_v2v4_MSP = melt(df.sample_metadata_metaG_v2v4_MSP)
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, variable = factor(variable, labels=c("Streptococcus thermophilus")))
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Visit = factor(Visit, labels=c("D0", "D28"), ordered=TRUE))
m.sample_metadata_metaG_v2v4_MSP =  transform(m.sample_metadata_metaG_v2v4_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.sample_metadata_metaG_v2v4_MSP$value[m.sample_metadata_metaG_v2v4_MSP$value == 0 ]=1e-11


my_comparisons <- list( c("FMP.3", "CP.3"))

p4=
 ggboxplot(m.sample_metadata_metaG_v2v4_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
              palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              # ylab = "Log10 relative abundance L. casei/paracasei",
              xlab= "",
              ggtheme = theme_pubr()) +
   scale_y_log10(name="Log10 relative abundance S. thermophilus") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))



tiff(file="~/actineo_paper/Rlocal_310719/MSP_actineo_AR_plot.tiff", w=800, h=600)
plot_grid(p1,p2,p3,p4, nrow=2, ncol=2)
dev.off()

```



# all samples n=107
```{r}

load("~/actineo_paper/Rlocal_310719/sample_metadata_metaG.rda")

sample_metadata_metaG$samplenr


sample_metadata_metaG = sample_metadata_metaG[match(rownames(MSP_relative_abundance_matrix_rounded_t),sample_metadata_metaG$samplenr),] 
all.equal(rownames(MSP_relative_abundance_matrix_rounded_t),sample_metadata_metaG$samplenr)

MSP_relative_abundance_matrix_rounded_t$sample = rownames(MSP_relative_abundance_matrix_rounded_t)

sample_metadata_metaG_MSP = merge(sample_metadata_metaG, MSP_relative_abundance_matrix_rounded_t, by.x="samplenr", by.y="sample")

sample_metadata_metaG_MSP %>% head

sample_metadata_metaG_MSP$Groupe_dose = as.factor(sample_metadata_metaG_MSP$Groupe_dose)

sample_metadata_metaG_MSP$Visit = as.factor(sample_metadata_metaG_MSP$Visit)

sample_metadata_metaG_MSP$Groupe_dose = relevel(sample_metadata_metaG_MSP$Groupe_dose, ref = "CP.3") 

summary(sample_metadata_metaG_MSP)
save(sample_metadata_metaG_MSP, file="~/actineo_paper/Rlocal_310719/sample_metadata_metaG_MSP.rda")




# plot L. rhamnosus

df.sample_metadata_metaG_MSP = data.frame(sample_metadata_metaG_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_lrhamnosus")])
m.df.sample_metadata_metaG_MSP = melt(df.sample_metadata_metaG_MSP)
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, variable = factor(variable, labels=c("Lactobacillus rhamnosus")))
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Visit = factor(Visit, labels=c("D0", "D28","D56"), ordered=TRUE))


m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.df.sample_metadata_metaG_MSP$value[m.df.sample_metadata_metaG_MSP$value == 0 ]=1e-11

# m.sample_metadata_metaG_v2v4_MSP_Lacto_filterv2v4 = m.sample_metadata_metaG_MSP_Lacto %>% filter(Visit == "D0" | Visit == "D28")

my_comparisons <- list( c("FMP.3", "CP.3"))

p1=
 ggboxplot(m.df.sample_metadata_metaG_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
            palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              ylab = "Log10 relative abundance L. rhamnosus",
              xlab= "",
              ggtheme = theme_pubr()) +
# scale_y_continuous(name = 'Gene richness', limits=c(0,1300000)) +
   scale_y_log10(name="Log10 relative abundance L. rhamnosus") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))



# msp_1025 Lactobacillus casei paracasei


df.sample_metadata_metaG_MSP = data.frame(sample_metadata_metaG_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_1025")])
m.df.sample_metadata_metaG_MSP = melt(df.sample_metadata_metaG_MSP)
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, variable = factor(variable, labels=c("Lactobacillus casei/paracasei")))
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Visit = factor(Visit, labels=c("D0", "D28","D56"), ordered=TRUE))
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.df.sample_metadata_metaG_MSP$value[m.df.sample_metadata_metaG_MSP$value == 0 ]=1e-11


my_comparisons <- list( c("FMP.3", "CP.3"))

p2=
 ggboxplot(m.df.sample_metadata_metaG_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
              palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              # ylab = "Log10 relative abundance L. casei/paracasei",
              xlab= "",
              ggtheme = theme_pubr()) +
   scale_y_log10(name="Log10 relative abundance L. casei/paracasei") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))



# msp_1200 Lactobacillus delbruckii

df.sample_metadata_metaG_MSP = data.frame(sample_metadata_metaG_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_1200")])
m.df.sample_metadata_metaG_MSP = melt(df.sample_metadata_metaG_MSP)
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, variable = factor(variable, labels=c("Lactobacillus delbruckii")))
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Visit = factor(Visit, labels=c("D0", "D28","D56"), ordered=TRUE))
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.df.sample_metadata_metaG_MSP$value[m.df.sample_metadata_metaG_MSP$value == 0 ]=1e-11


my_comparisons <- list( c("FMP.3", "CP.3"))


p3=
 ggboxplot(m.df.sample_metadata_metaG_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
            palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              # ylab = "Log10 Relative abundance L. amylovorus",
              xlab= "",
              ggtheme = theme_pubr()) +
   scale_y_log10(name="Log10 relative abundance L. delbruckii") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))


# msp_0970 Streptococcus thermophilus


df.sample_metadata_metaG_MSP = data.frame(sample_metadata_metaG_MSP[,c("Visit","Groupe_dose", "Groupe", "group","msp_0790")])
m.df.sample_metadata_metaG_MSP = melt(df.sample_metadata_metaG_MSP)
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, variable = factor(variable, labels=c("Streptococcus thermophilus")))
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Visit = factor(Visit, labels=c("D0", "D28","D56"), ordered=TRUE))
m.df.sample_metadata_metaG_MSP =  transform(m.df.sample_metadata_metaG_MSP, Groupe_dose = factor(Groupe_dose, labels=c("CP.3", "FMP.3"), ordered=TRUE))


m.df.sample_metadata_metaG_MSP$value[m.df.sample_metadata_metaG_MSP$value == 0 ]=1e-11


my_comparisons <- list( c("FMP.3", "CP.3"))

p4=
 ggboxplot(m.df.sample_metadata_metaG_MSP, x = "Groupe_dose", y = "value",
            color = "Groupe_dose", 
            fill="Groupe_dose",
            alpha=0.5,
              palette=c("#3399FF", "#FF0033"),
              add = "jitter",
              # ylab = "Log10 relative abundance L. casei/paracasei",
              xlab= "",
              ggtheme = theme_pubr()) +
   scale_y_log10(name="Log10 relative abundance S. thermophilus") +
   stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
   theme(axis.title.x=element_blank(), legend.position = 'none')+
 facet_grid(. ~ Visit)+
  theme(strip.text.x = element_text(size=13, color="white", face="bold")) +
  theme(strip.background = element_rect(colour="white", fill="gray48", linetype="solid"))+
  theme(axis.title.x = element_text(color="black", face="bold", size=13),
        axis.title.y = element_text(color="black", size=12, face="bold"),
        axis.text.y = element_text(color="black", size=10, face="bold"),
        axis.text.x = element_text(color="black", size=10, face="bold"),
        legend.text = element_text(color="black", size=10, face="bold"),
        legend.title = element_text(color="black", size=13, face="bold"))



tiff(file="~/actineo_paper/Rlocal_310719/MSP_actineo_AR_plot_107samples.tiff", w=800, h=600)
plot_grid(p1,p2,p3,p4, nrow=2, ncol=2)
dev.off()




```