#---
title: "scaled gene count matrix preprocessing"
output: html_notebook
#---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DESeq2)
library(ggplot2)
library(foreach)
library(readr)
library(momr)
source("/home/alvareao/momr_1.1_corrections_v2.R")
devtools::load_all(reset=FALSE)

```


```{r}

## download raw scaled gene abundance matrix -------------------
profile_tolerance_scaled_raw = read_tsv("/home/alvareao/tolerance/data-raw/scaled_normalization_counts.txt")

profile_tolerance_scaled_raw = as.data.frame(profile_tolerance_scaled_raw)
save(profile_tolerance_scaled_raw, file="profile_tolerance_scaled_raw.rda")
profile_tolerance_scaled = profile_tolerance_scaled_raw[-1,-1]
profile_tolerance_scaled = as.matrix(profile_tolerance_scaled)
save(profile_tolerance_scaled, file="profile_tolerance_scaled.rda")

## round scaled gene abundance matrix -------------------
profile_tolerance_scaled_rounded = round(profile_tolerance_scaled)
save(profile_tolerance_scaled_rounded, file="profile_tolerance_scaled_rounded.rda")
load("/home/alvareao/tolerance/data-raw/profile_tolerance_scaled_rounded.rda")


## change of rownames and colnames of the rounded scaled matrix ------
load("~/tolerance/data-raw/profile_tolerance_scaled_raw.rda")
rownames(profile_tolerance_scaled_raw) = profile_tolerance_scaled_raw$X1
profile_tolerance_scaled_raw = profile_tolerance_scaled_raw[-1,-1]

rownames(profile_tolerance_scaled_rounded)= gsub('\\|MetaHIT$',"",rownames(profile_tolerance_scaled_raw))

Tolerance::sample_metadata_metaG %>% head
colnames(profile_tolerance_scaled_rounded) = sample_metadata_metaG$samplenr
head(profile_tolerance_scaled_rounded)
save(profile_tolerance_scaled_rounded, file="profile_tolerance_scaled_rounded_final.RData", compress=T)

load("~/tolerance/data-raw/profile_tolerance_scaled_rounded_final.RData")


profile_tolerance_scaled_rounded_nonull = profile_tolerance_scaled_rounded[rowSums(profile_tolerance_scaled_rounded)>0,]
save(profile_tolerance_scaled_rounded_nonull, file="profile_tolerance_scaled_rounded_nonull_final_nonull.Rdata", compress=T)



```



