---
title: "MSP L rhamnosus integration"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}

library(dplyr)
devtools::load_all(reset=FALSE)
library(readr)
library(foreach)
library(doMC)
registerDoMC(detectCores())

```

```{r}

# download L rhamnosus cdhit file (cdhit 95 90 on the L_rhamnosus non redundant fna)

Lrhamnosus = read_tsv("~/tolerance/data-raw/L_rhamnosus_pangenome_nonredundant.fna.clstr.txt")
Lrhamnosus %>% head

# downlaod MSP catalog tolerance file (without L rhamnosus MSP)

load("~/tolerance/data-raw/msp2018_tolerance_catalog_table.rda")
msp2018_tolerance_catalog_table %>% head
msp2018 = msp2018_tolerance_catalog_table

str(msp2018)
#  $ msp_name   : chr  "msp_0001" "msp_0001" "msp_0001" "msp_0001" ...
#  $ module_name: chr  "core" "core" "core" "core" ...
#  $ gene_id    : int  49450 593406 26346 952522 22630 83641 4566207 12929 864059 370104 ...
#  $ gene_name  : chr  "159268001-stool1_revised_scaffold2795_1_gene123456" "159268001-stool2_revised_scaffold25897_1_gene17563" "159268001-stool2_revised_scaffold29829_1_gene14363" "764487809-stool2_revised_C884597_1_gene165835" ...
#  $ gene_length: int  3894 1794 4632 1491 4869 3366 618 5862 1548 2127 ...


# match on the 2 files

Lrhamnosus_rep1=subset(Lrhamnosus, clstr_rep==1)
msp2018$gene_name=Lrhamnosus_rep1$id[match(msp2018$clstr,Lrhamnosus_rep1$clstr)]
msp2018 %>% head
## no match -> NA


# build file L rhamnosus with the same colnames that the MSP toelrance catalog file

Lrhamnosus_m = as.data.frame(Lrhamnosus)
Lrhamnosus_m$msp_name = "msp_lrhamnosus"
Lrhamnosus_m$module_name = "core"
Lrhamnosus_m$gene_name = Lrhamnosus$id

str(Lrhamnosus_m)
Lrhamnosus_m=subset(Lrhamnosus_m, clstr_rep==1)
Lrhamnosus_m = Lrhamnosus_m[, c(8:10)]
#6702 genes

# gene length of the L rhamnosus non redundant fna (server)
Lrhamnosus_gene_length = read_tsv("~/tolerance/data-raw/L_rhamnosus_pangenome_nonredundant.genes_length.tsv")
head(Lrhamnosus_gene_length)
Lrhamnosus_gene_length$gene_name


Lrhamnosus_gene_length=Lrhamnosus_gene_length[match(Lrhamnosus_m$gene_name,Lrhamnosus_gene_length$gene_name)]


```
